// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.paytm.web.provider.recharge;


public class PaytmRechargeSIE_recharge_ResponseStruct1 {
    protected java.util.List result;
    
    public PaytmRechargeSIE_recharge_ResponseStruct1() {
    }
    
    public PaytmRechargeSIE_recharge_ResponseStruct1(java.util.List result) {
        this.result = result;
    }
    
    public java.util.List getResult() {
        return result;
    }
    
    public void setResult(java.util.List result) {
        this.result = result;
    }
}
