// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.paytm.web.provider.recharge;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.util.exception.LocalizableExceptionAdapter;

public class PaytmRechargeSIE_recharge2_RequestStruct_SOAPBuilder implements SOAPInstanceBuilder {
    private com.paytm.web.provider.recharge.PaytmRechargeSIE_recharge2_RequestStruct _instance;
    private long long_1;
    private java.lang.String String_2;
    private java.lang.String String_3;
    private static final int myLONG_1_INDEX = 0;
    private static final int mySTRING_2_INDEX = 1;
    private static final int mySTRING_3_INDEX = 2;
    
    public PaytmRechargeSIE_recharge2_RequestStruct_SOAPBuilder() {
    }
    
    public void setLong_1(long long_1) {
        this.long_1 = long_1;
    }
    
    public void setString_2(java.lang.String String_2) {
        this.String_2 = String_2;
    }
    
    public void setString_3(java.lang.String String_3) {
        this.String_3 = String_3;
    }
    
    public int memberGateType(int memberIndex) {
        switch (memberIndex) {
            case mySTRING_2_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case mySTRING_3_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            default:
                throw new IllegalArgumentException();
        }
    }
    
    public void construct() {
    }
    
    public void setMember(int index, java.lang.Object memberValue) {
        try {
            switch(index) {
                case mySTRING_2_INDEX:
                    _instance.setString_2((java.lang.String)memberValue);
                    break;
                case mySTRING_3_INDEX:
                    _instance.setString_3((java.lang.String)memberValue);
                    break;
                default:
                    throw new java.lang.IllegalArgumentException();
            }
        }
        catch (java.lang.RuntimeException e) {
            throw e;
        }
        catch (java.lang.Exception e) {
            throw new DeserializationException(new LocalizableExceptionAdapter(e));
        }
    }
    
    public void initialize() {
    }
    
    public void setInstance(java.lang.Object instance) {
        _instance = (com.paytm.web.provider.recharge.PaytmRechargeSIE_recharge2_RequestStruct)instance;
    }
    
    public java.lang.Object getInstance() {
        return _instance;
    }
}
