// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.paytm.web.provider.recharge;


public class PaytmRechargeSIE_recharge_RequestStruct {
    protected long long_1;
    
    public PaytmRechargeSIE_recharge_RequestStruct() {
    }
    
    public PaytmRechargeSIE_recharge_RequestStruct(long long_1) {
        this.long_1 = long_1;
    }
    
    public long getLong_1() {
        return long_1;
    }
    
    public void setLong_1(long long_1) {
        this.long_1 = long_1;
    }
}
