// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package in.co.irctc.web.provider;

import com.sun.xml.rpc.server.http.MessageContextProperties;
import com.sun.xml.rpc.streaming.*;
import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.soap.SOAPConstants;
import com.sun.xml.rpc.encoding.soap.SOAP12Constants;
import com.sun.xml.rpc.encoding.literal.*;
import com.sun.xml.rpc.soap.streaming.*;
import com.sun.xml.rpc.soap.message.*;
import com.sun.xml.rpc.soap.SOAPVersion;
import com.sun.xml.rpc.soap.SOAPEncodingConstants;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;
import javax.xml.namespace.QName;
import java.rmi.RemoteException;
import java.util.Iterator;
import java.lang.reflect.*;
import java.lang.Class;
import com.sun.xml.rpc.server.*;
import javax.xml.rpc.handler.HandlerInfo;
import com.sun.xml.rpc.client.HandlerChainImpl;

public class IRCTCServiceSIE_Tie
    extends com.sun.xml.rpc.server.TieBase implements SerializerConstants {
    
    
    
    public IRCTCServiceSIE_Tie() throws Exception {
        super(new in.co.irctc.service.bindings.IRCTCService_SerializerRegistry().getRegistry());
        initialize(internalTypeMappingRegistry);
    }
    
    /*
     * This method does the actual method invocation for operation: getTicketPrice
     */
    private void invoke_getTicketPrice(StreamingHandlerState state) throws Exception {
        
        in.co.irctc.web.provider.IRCTCServiceSIE_getTicketPrice_RequestStruct myIRCTCServiceSIE_getTicketPrice_RequestStruct = null;
        Object myIRCTCServiceSIE_getTicketPrice_RequestStructObj =
            state.getRequest().getBody().getValue();
        
        if (myIRCTCServiceSIE_getTicketPrice_RequestStructObj instanceof SOAPDeserializationState) {
            myIRCTCServiceSIE_getTicketPrice_RequestStruct = (in.co.irctc.web.provider.IRCTCServiceSIE_getTicketPrice_RequestStruct)((SOAPDeserializationState)myIRCTCServiceSIE_getTicketPrice_RequestStructObj).getInstance();
        } else {
            myIRCTCServiceSIE_getTicketPrice_RequestStruct = (in.co.irctc.web.provider.IRCTCServiceSIE_getTicketPrice_RequestStruct)myIRCTCServiceSIE_getTicketPrice_RequestStructObj;
        }
        
        try {
            double result = 
                ((in.co.irctc.web.provider.IRCTCServiceSIE) getTarget()).getTicketPrice(myIRCTCServiceSIE_getTicketPrice_RequestStruct.getJourneyInfo_1());
            in.co.irctc.web.provider.IRCTCServiceSIE_getTicketPrice_ResponseStruct myIRCTCServiceSIE_getTicketPrice_ResponseStruct =
                new in.co.irctc.web.provider.IRCTCServiceSIE_getTicketPrice_ResponseStruct();
            SOAPHeaderBlockInfo headerInfo;
            myIRCTCServiceSIE_getTicketPrice_ResponseStruct.setResult(result);
            
            SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_getTicketPrice_getTicketPriceResponse_QNAME);
            bodyBlock.setValue(myIRCTCServiceSIE_getTicketPrice_ResponseStruct);
            bodyBlock.setSerializer(ns2_myIRCTCServiceSIE_getTicketPrice_ResponseStruct_SOAPSerializer);
            state.getResponse().setBody(bodyBlock);
        } catch (javax.xml.rpc.soap.SOAPFaultException e) {
            SOAPFaultInfo fault = new SOAPFaultInfo(e.getFaultCode(),
                e.getFaultString(), e.getFaultActor(), e.getDetail());
            SOAPBlockInfo faultBlock = new SOAPBlockInfo(com.sun.xml.rpc.encoding.soap.SOAPConstants.QNAME_SOAP_FAULT);
            faultBlock.setValue(fault);
            faultBlock.setSerializer(new SOAPFaultInfoSerializer(false, e.getDetail()==null));
            state.getResponse().setBody(faultBlock);
            state.getResponse().setFailure(true);
        }
    }
    
    /*
     * This method does the actual method invocation for operation: bootTicket
     */
    private void invoke_bootTicket(StreamingHandlerState state) throws Exception {
        
        in.co.irctc.web.provider.IRCTCServiceSIE_bootTicket_RequestStruct myIRCTCServiceSIE_bootTicket_RequestStruct = null;
        Object myIRCTCServiceSIE_bootTicket_RequestStructObj =
            state.getRequest().getBody().getValue();
        
        if (myIRCTCServiceSIE_bootTicket_RequestStructObj instanceof SOAPDeserializationState) {
            myIRCTCServiceSIE_bootTicket_RequestStruct = (in.co.irctc.web.provider.IRCTCServiceSIE_bootTicket_RequestStruct)((SOAPDeserializationState)myIRCTCServiceSIE_bootTicket_RequestStructObj).getInstance();
        } else {
            myIRCTCServiceSIE_bootTicket_RequestStruct = (in.co.irctc.web.provider.IRCTCServiceSIE_bootTicket_RequestStruct)myIRCTCServiceSIE_bootTicket_RequestStructObj;
        }
        
        try {
            in.co.irctc.web.provider.pojo.Ticket result = 
                ((in.co.irctc.web.provider.IRCTCServiceSIE) getTarget()).bootTicket(myIRCTCServiceSIE_bootTicket_RequestStruct.getJourneyInfo_1(), myIRCTCServiceSIE_bootTicket_RequestStruct.getPassengerInfo_2());
            in.co.irctc.web.provider.IRCTCServiceSIE_bootTicket_ResponseStruct myIRCTCServiceSIE_bootTicket_ResponseStruct =
                new in.co.irctc.web.provider.IRCTCServiceSIE_bootTicket_ResponseStruct();
            SOAPHeaderBlockInfo headerInfo;
            myIRCTCServiceSIE_bootTicket_ResponseStruct.setResult(result);
            
            SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_bootTicket_bootTicketResponse_QNAME);
            bodyBlock.setValue(myIRCTCServiceSIE_bootTicket_ResponseStruct);
            bodyBlock.setSerializer(ns2_myIRCTCServiceSIE_bootTicket_ResponseStruct_SOAPSerializer);
            state.getResponse().setBody(bodyBlock);
        } catch (javax.xml.rpc.soap.SOAPFaultException e) {
            SOAPFaultInfo fault = new SOAPFaultInfo(e.getFaultCode(),
                e.getFaultString(), e.getFaultActor(), e.getDetail());
            SOAPBlockInfo faultBlock = new SOAPBlockInfo(com.sun.xml.rpc.encoding.soap.SOAPConstants.QNAME_SOAP_FAULT);
            faultBlock.setValue(fault);
            faultBlock.setSerializer(new SOAPFaultInfoSerializer(false, e.getDetail()==null));
            state.getResponse().setBody(faultBlock);
            state.getResponse().setFailure(true);
        }
    }
    
    /*
     * This method must determine the opcode of the operation that has been invoked.
     */
    protected void peekFirstBodyElement(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingHandlerState state) throws Exception {
        if (bodyReader.getName().equals(ns1_getTicketPrice_getTicketPrice_QNAME)) {
            state.getRequest().setOperationCode(getTicketPrice_OPCODE);
        }
        else if (bodyReader.getName().equals(ns1_bootTicket_bootTicket_QNAME)) {
            state.getRequest().setOperationCode(bootTicket_OPCODE);
        }
        else {
            throw new SOAPProtocolViolationException("soap.operation.unrecognized", bodyReader.getName().toString());
        }
    }
    
    /*
     *  this method deserializes the request/response structure in the body
     */
    protected void readFirstBodyElement(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingHandlerState  state) throws Exception {
        int opcode = state.getRequest().getOperationCode();
        switch (opcode) {
            case getTicketPrice_OPCODE:
                deserialize_getTicketPrice(bodyReader, deserializationContext, state);
                break;
            case bootTicket_OPCODE:
                deserialize_bootTicket(bodyReader, deserializationContext, state);
                break;
            default:
                throw new SOAPProtocolViolationException("soap.operation.unrecognized", java.lang.Integer.toString(opcode));
        }
    }
    
    
    
    /*
     * This method deserializes the body of the getTicketPrice operation.
     */
    private void deserialize_getTicketPrice(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingHandlerState state) throws Exception {
        java.lang.Object myIRCTCServiceSIE_getTicketPrice_RequestStructObj =
            ns2_myIRCTCServiceSIE_getTicketPrice_RequestStruct_SOAPSerializer.deserialize(ns1_getTicketPrice_getTicketPrice_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_getTicketPrice_getTicketPrice_QNAME);
        bodyBlock.setValue(myIRCTCServiceSIE_getTicketPrice_RequestStructObj);
        state.getRequest().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the bootTicket operation.
     */
    private void deserialize_bootTicket(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingHandlerState state) throws Exception {
        java.lang.Object myIRCTCServiceSIE_bootTicket_RequestStructObj =
            ns2_myIRCTCServiceSIE_bootTicket_RequestStruct_SOAPSerializer.deserialize(ns1_bootTicket_bootTicket_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_bootTicket_bootTicket_QNAME);
        bodyBlock.setValue(myIRCTCServiceSIE_bootTicket_RequestStructObj);
        state.getRequest().setBody(bodyBlock);
    }
    
    
    /*
     * This method must invoke the correct method on the servant based on the opcode.
     */
    protected void processingHook(StreamingHandlerState state) throws Exception {
        switch (state.getRequest().getOperationCode()) {
            case getTicketPrice_OPCODE:
                invoke_getTicketPrice(state);
                break;
            case bootTicket_OPCODE:
                invoke_bootTicket(state);
                break;
            default:
                throw new SOAPProtocolViolationException("soap.operation.unrecognized", java.lang.Integer.toString(state.getRequest().getOperationCode()));
        }
    }
    
    public java.lang.String getDefaultEnvelopeEncodingStyle() {
        return SOAPNamespaceConstants.ENCODING;
    }
    
    public java.lang.String getImplicitEnvelopeEncodingStyle() {
        return "";
    }
    
    
    /*
     * This method must determine the opcode of the operation given the QName of the first body element.
     */
    public int getOpcodeForFirstBodyElementName(QName name) {
        if (name == null) {
            return InternalSOAPMessage.NO_OPERATION;
        }
        if (name.equals(ns1_getTicketPrice_getTicketPrice_QNAME)) {
            return getTicketPrice_OPCODE;
        }
        if (name.equals(ns1_bootTicket_bootTicket_QNAME)) {
            return bootTicket_OPCODE;
        }
        return super.getOpcodeForFirstBodyElementName(name);
    }
    
    
    private Method internalGetMethodForOpcode(int opcode) throws ClassNotFoundException, NoSuchMethodException {
        
        Method theMethod = null;
        
        switch(opcode) {
            case getTicketPrice_OPCODE:
                {
                    Class[] carray = { in.co.irctc.web.provider.pojo.JourneyInfo.class };
                    theMethod = (in.co.irctc.web.provider.IRCTCServiceSIE.class).getMethod("getTicketPrice", carray);
                }
                break;
            
            case bootTicket_OPCODE:
                {
                    Class[] carray = { in.co.irctc.web.provider.pojo.JourneyInfo.class,in.co.irctc.web.provider.pojo.PassengerInfo.class };
                    theMethod = (in.co.irctc.web.provider.IRCTCServiceSIE.class).getMethod("bootTicket", carray);
                }
                break;
            
            default:
        }
        return theMethod;
    }
    
    private Method[] methodMap = new Method[2];
    
    /*
     * This method returns the Method Obj for a specified opcode.
     */
    public Method getMethodForOpcode(int opcode) throws ClassNotFoundException, NoSuchMethodException {
         
        if (opcode <= InternalSOAPMessage.NO_OPERATION ) {
            return null;
        }
         
        if (opcode >= 2 ) {
            return null;
        }
         
        if (methodMap[opcode] == null)  {
            methodMap[opcode] = internalGetMethodForOpcode(opcode);
        }
         
        return methodMap[opcode];
    }
    
    /*
     * This method returns an array containing (prefix, nsURI) pairs.
     */
    protected java.lang.String[] getNamespaceDeclarations() {
        return myNamespace_declarations;
    }
    
    /*
     * This method returns an array containing the names of the headers we understand.
     */
    public javax.xml.namespace.QName[] getUnderstoodHeaders() {
        return understoodHeaderNames;
    }
    
    
    protected boolean preHandlingHook(StreamingHandlerState state) throws Exception {
        boolean bool = false;
        bool = super.preHandlingHook(state);
        return bool;
    }
    
    
    protected void postResponseWritingHook(StreamingHandlerState state) throws Exception {
        super.postResponseWritingHook(state);
    }
    
    private void initialize(InternalTypeMappingRegistry registry) throws Exception {
        ns2_myIRCTCServiceSIE_bootTicket_ResponseStruct_SOAPSerializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, in.co.irctc.web.provider.IRCTCServiceSIE_bootTicket_ResponseStruct.class, ns2_bootTicketResponse_TYPE_QNAME);
        ns2_myIRCTCServiceSIE_getTicketPrice_ResponseStruct_SOAPSerializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, in.co.irctc.web.provider.IRCTCServiceSIE_getTicketPrice_ResponseStruct.class, ns2_getTicketPriceResponse_TYPE_QNAME);
        ns2_myIRCTCServiceSIE_getTicketPrice_RequestStruct_SOAPSerializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, in.co.irctc.web.provider.IRCTCServiceSIE_getTicketPrice_RequestStruct.class, ns2_getTicketPrice_TYPE_QNAME);
        ns2_myIRCTCServiceSIE_bootTicket_RequestStruct_SOAPSerializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, in.co.irctc.web.provider.IRCTCServiceSIE_bootTicket_RequestStruct.class, ns2_bootTicket_TYPE_QNAME);
    }
    
    private static final javax.xml.namespace.QName portName = new QName("http://irctc.co.in/partners/ticketsinfo/service", "IRCTCServiceSIE");
    private static final int getTicketPrice_OPCODE = 0;
    private static final int bootTicket_OPCODE = 1;
    private static final javax.xml.namespace.QName ns1_getTicketPrice_getTicketPrice_QNAME = new QName("http://irctc.co.in/partners/ticketsinfo/service", "getTicketPrice");
    private static final javax.xml.namespace.QName ns2_getTicketPrice_TYPE_QNAME = new QName("http://irctc.co.in/partners/ticketsinfo/types", "getTicketPrice");
    private CombinedSerializer ns2_myIRCTCServiceSIE_getTicketPrice_RequestStruct_SOAPSerializer;
    private static final javax.xml.namespace.QName ns1_getTicketPrice_getTicketPriceResponse_QNAME = new QName("http://irctc.co.in/partners/ticketsinfo/service", "getTicketPriceResponse");
    private static final javax.xml.namespace.QName ns2_getTicketPriceResponse_TYPE_QNAME = new QName("http://irctc.co.in/partners/ticketsinfo/types", "getTicketPriceResponse");
    private CombinedSerializer ns2_myIRCTCServiceSIE_getTicketPrice_ResponseStruct_SOAPSerializer;
    private static final javax.xml.namespace.QName ns1_bootTicket_bootTicket_QNAME = new QName("http://irctc.co.in/partners/ticketsinfo/service", "bootTicket");
    private static final javax.xml.namespace.QName ns2_bootTicket_TYPE_QNAME = new QName("http://irctc.co.in/partners/ticketsinfo/types", "bootTicket");
    private CombinedSerializer ns2_myIRCTCServiceSIE_bootTicket_RequestStruct_SOAPSerializer;
    private static final javax.xml.namespace.QName ns1_bootTicket_bootTicketResponse_QNAME = new QName("http://irctc.co.in/partners/ticketsinfo/service", "bootTicketResponse");
    private static final javax.xml.namespace.QName ns2_bootTicketResponse_TYPE_QNAME = new QName("http://irctc.co.in/partners/ticketsinfo/types", "bootTicketResponse");
    private CombinedSerializer ns2_myIRCTCServiceSIE_bootTicket_ResponseStruct_SOAPSerializer;
    private static final java.lang.String[] myNamespace_declarations =
                                        new java.lang.String[] {
                                            "ns0", "http://irctc.co.in/partners/ticketsinfo/types"
                                        };
    
    private static final QName[] understoodHeaderNames = new QName[] {  };
}
