// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package in.co.irctc.web.provider;


public class IRCTCServiceSIE_bootTicket_ResponseStruct {
    protected in.co.irctc.web.provider.pojo.Ticket result;
    
    public IRCTCServiceSIE_bootTicket_ResponseStruct() {
    }
    
    public IRCTCServiceSIE_bootTicket_ResponseStruct(in.co.irctc.web.provider.pojo.Ticket result) {
        this.result = result;
    }
    
    public in.co.irctc.web.provider.pojo.Ticket getResult() {
        return result;
    }
    
    public void setResult(in.co.irctc.web.provider.pojo.Ticket result) {
        this.result = result;
    }
}
