// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package in.co.irctc.web.provider;


public class IRCTCServiceSIE_getTicketPrice_ResponseStruct {
    protected double result;
    
    public IRCTCServiceSIE_getTicketPrice_ResponseStruct() {
    }
    
    public IRCTCServiceSIE_getTicketPrice_ResponseStruct(double result) {
        this.result = result;
    }
    
    public double getResult() {
        return result;
    }
    
    public void setResult(double result) {
        this.result = result;
    }
}
