// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package in.co.irctc.web.provider;


public class IRCTCServiceSIE_getTicketPrice_RequestStruct {
    protected in.co.irctc.web.provider.JourneyInfo JourneyInfo_1;
    
    public IRCTCServiceSIE_getTicketPrice_RequestStruct() {
    }
    
    public IRCTCServiceSIE_getTicketPrice_RequestStruct(in.co.irctc.web.provider.JourneyInfo JourneyInfo_1) {
        this.JourneyInfo_1 = JourneyInfo_1;
    }
    
    public in.co.irctc.web.provider.JourneyInfo getJourneyInfo_1() {
        return JourneyInfo_1;
    }
    
    public void setJourneyInfo_1(in.co.irctc.web.provider.JourneyInfo JourneyInfo_1) {
        this.JourneyInfo_1 = JourneyInfo_1;
    }
}
