// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.paytm.web.provider;

import com.sun.xml.rpc.server.http.MessageContextProperties;
import com.sun.xml.rpc.streaming.*;
import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.soap.SOAPConstants;
import com.sun.xml.rpc.encoding.soap.SOAP12Constants;
import com.sun.xml.rpc.encoding.literal.*;
import com.sun.xml.rpc.soap.streaming.*;
import com.sun.xml.rpc.soap.message.*;
import com.sun.xml.rpc.soap.SOAPVersion;
import com.sun.xml.rpc.soap.SOAPEncodingConstants;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;
import javax.xml.namespace.QName;
import java.rmi.RemoteException;
import java.util.Iterator;
import java.lang.reflect.*;
import java.lang.Class;
import com.sun.xml.rpc.server.*;
import javax.xml.rpc.handler.HandlerInfo;
import com.sun.xml.rpc.client.HandlerChainImpl;

public class PaytmMovieSIE_Tie
    extends com.sun.xml.rpc.server.TieBase implements SerializerConstants {
    
    
    
    public PaytmMovieSIE_Tie() throws Exception {
        super(new com.paytm.service.bindings.PaytmService_SerializerRegistry().getRegistry());
        initialize(internalTypeMappingRegistry);
    }
    
    /*
     * This method does the actual method invocation for operation: cancelTicket
     */
    private void invoke_cancelTicket(StreamingHandlerState state) throws Exception {
        
        com.paytm.web.provider.PaytmMovieSIE_cancelTicket_RequestStruct myPaytmMovieSIE_cancelTicket_RequestStruct = null;
        Object myPaytmMovieSIE_cancelTicket_RequestStructObj =
            state.getRequest().getBody().getValue();
        
        if (myPaytmMovieSIE_cancelTicket_RequestStructObj instanceof SOAPDeserializationState) {
            myPaytmMovieSIE_cancelTicket_RequestStruct = (com.paytm.web.provider.PaytmMovieSIE_cancelTicket_RequestStruct)((SOAPDeserializationState)myPaytmMovieSIE_cancelTicket_RequestStructObj).getInstance();
        } else {
            myPaytmMovieSIE_cancelTicket_RequestStruct = (com.paytm.web.provider.PaytmMovieSIE_cancelTicket_RequestStruct)myPaytmMovieSIE_cancelTicket_RequestStructObj;
        }
        
        try {
            java.lang.String result = 
                ((com.paytm.web.provider.PaytmMovieSIE) getTarget()).cancelTicket(myPaytmMovieSIE_cancelTicket_RequestStruct.getString_1());
            com.paytm.web.provider.PaytmMovieSIE_cancelTicket_ResponseStruct myPaytmMovieSIE_cancelTicket_ResponseStruct =
                new com.paytm.web.provider.PaytmMovieSIE_cancelTicket_ResponseStruct();
            SOAPHeaderBlockInfo headerInfo;
            myPaytmMovieSIE_cancelTicket_ResponseStruct.setResult(result);
            
            SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_cancelTicket_cancelTicketResponse_QNAME);
            bodyBlock.setValue(myPaytmMovieSIE_cancelTicket_ResponseStruct);
            bodyBlock.setSerializer(ns2_myPaytmMovieSIE_cancelTicket_ResponseStruct_SOAPSerializer);
            state.getResponse().setBody(bodyBlock);
        } catch (javax.xml.rpc.soap.SOAPFaultException e) {
            SOAPFaultInfo fault = new SOAPFaultInfo(e.getFaultCode(),
                e.getFaultString(), e.getFaultActor(), e.getDetail());
            SOAPBlockInfo faultBlock = new SOAPBlockInfo(com.sun.xml.rpc.encoding.soap.SOAPConstants.QNAME_SOAP_FAULT);
            faultBlock.setValue(fault);
            faultBlock.setSerializer(new SOAPFaultInfoSerializer(false, e.getDetail()==null));
            state.getResponse().setBody(faultBlock);
            state.getResponse().setFailure(true);
        }
    }
    
    /*
     * This method does the actual method invocation for operation: bookMovieTicket
     */
    private void invoke_bookMovieTicket(StreamingHandlerState state) throws Exception {
        
        com.paytm.web.provider.PaytmMovieSIE_bookMovieTicket_RequestStruct myPaytmMovieSIE_bookMovieTicket_RequestStruct = null;
        Object myPaytmMovieSIE_bookMovieTicket_RequestStructObj =
            state.getRequest().getBody().getValue();
        
        if (myPaytmMovieSIE_bookMovieTicket_RequestStructObj instanceof SOAPDeserializationState) {
            myPaytmMovieSIE_bookMovieTicket_RequestStruct = (com.paytm.web.provider.PaytmMovieSIE_bookMovieTicket_RequestStruct)((SOAPDeserializationState)myPaytmMovieSIE_bookMovieTicket_RequestStructObj).getInstance();
        } else {
            myPaytmMovieSIE_bookMovieTicket_RequestStruct = (com.paytm.web.provider.PaytmMovieSIE_bookMovieTicket_RequestStruct)myPaytmMovieSIE_bookMovieTicket_RequestStructObj;
        }
        
        try {
            java.lang.String result = 
                ((com.paytm.web.provider.PaytmMovieSIE) getTarget()).bookMovieTicket(myPaytmMovieSIE_bookMovieTicket_RequestStruct.getString_1(), myPaytmMovieSIE_bookMovieTicket_RequestStruct.getString_2());
            com.paytm.web.provider.PaytmMovieSIE_bookMovieTicket_ResponseStruct myPaytmMovieSIE_bookMovieTicket_ResponseStruct =
                new com.paytm.web.provider.PaytmMovieSIE_bookMovieTicket_ResponseStruct();
            SOAPHeaderBlockInfo headerInfo;
            myPaytmMovieSIE_bookMovieTicket_ResponseStruct.setResult(result);
            
            SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_bookMovieTicket_bookMovieTicketResponse_QNAME);
            bodyBlock.setValue(myPaytmMovieSIE_bookMovieTicket_ResponseStruct);
            bodyBlock.setSerializer(ns2_myPaytmMovieSIE_bookMovieTicket_ResponseStruct_SOAPSerializer);
            state.getResponse().setBody(bodyBlock);
        } catch (javax.xml.rpc.soap.SOAPFaultException e) {
            SOAPFaultInfo fault = new SOAPFaultInfo(e.getFaultCode(),
                e.getFaultString(), e.getFaultActor(), e.getDetail());
            SOAPBlockInfo faultBlock = new SOAPBlockInfo(com.sun.xml.rpc.encoding.soap.SOAPConstants.QNAME_SOAP_FAULT);
            faultBlock.setValue(fault);
            faultBlock.setSerializer(new SOAPFaultInfoSerializer(false, e.getDetail()==null));
            state.getResponse().setBody(faultBlock);
            state.getResponse().setFailure(true);
        }
    }
    
    /*
     * This method must determine the opcode of the operation that has been invoked.
     */
    protected void peekFirstBodyElement(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingHandlerState state) throws Exception {
        if (bodyReader.getName().equals(ns1_cancelTicket_cancelTicket_QNAME)) {
            state.getRequest().setOperationCode(cancelTicket_OPCODE);
        }
        else if (bodyReader.getName().equals(ns1_bookMovieTicket_bookMovieTicket_QNAME)) {
            state.getRequest().setOperationCode(bookMovieTicket_OPCODE);
        }
        else {
            throw new SOAPProtocolViolationException("soap.operation.unrecognized", bodyReader.getName().toString());
        }
    }
    
    /*
     *  this method deserializes the request/response structure in the body
     */
    protected void readFirstBodyElement(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingHandlerState  state) throws Exception {
        int opcode = state.getRequest().getOperationCode();
        switch (opcode) {
            case cancelTicket_OPCODE:
                deserialize_cancelTicket(bodyReader, deserializationContext, state);
                break;
            case bookMovieTicket_OPCODE:
                deserialize_bookMovieTicket(bodyReader, deserializationContext, state);
                break;
            default:
                throw new SOAPProtocolViolationException("soap.operation.unrecognized", java.lang.Integer.toString(opcode));
        }
    }
    
    
    
    /*
     * This method deserializes the body of the cancelTicket operation.
     */
    private void deserialize_cancelTicket(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingHandlerState state) throws Exception {
        java.lang.Object myPaytmMovieSIE_cancelTicket_RequestStructObj =
            ns2_myPaytmMovieSIE_cancelTicket_RequestStruct_SOAPSerializer.deserialize(ns1_cancelTicket_cancelTicket_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_cancelTicket_cancelTicket_QNAME);
        bodyBlock.setValue(myPaytmMovieSIE_cancelTicket_RequestStructObj);
        state.getRequest().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the bookMovieTicket operation.
     */
    private void deserialize_bookMovieTicket(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingHandlerState state) throws Exception {
        java.lang.Object myPaytmMovieSIE_bookMovieTicket_RequestStructObj =
            ns2_myPaytmMovieSIE_bookMovieTicket_RequestStruct_SOAPSerializer.deserialize(ns1_bookMovieTicket_bookMovieTicket_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_bookMovieTicket_bookMovieTicket_QNAME);
        bodyBlock.setValue(myPaytmMovieSIE_bookMovieTicket_RequestStructObj);
        state.getRequest().setBody(bodyBlock);
    }
    
    
    /*
     * This method must invoke the correct method on the servant based on the opcode.
     */
    protected void processingHook(StreamingHandlerState state) throws Exception {
        switch (state.getRequest().getOperationCode()) {
            case cancelTicket_OPCODE:
                invoke_cancelTicket(state);
                break;
            case bookMovieTicket_OPCODE:
                invoke_bookMovieTicket(state);
                break;
            default:
                throw new SOAPProtocolViolationException("soap.operation.unrecognized", java.lang.Integer.toString(state.getRequest().getOperationCode()));
        }
    }
    
    public java.lang.String getDefaultEnvelopeEncodingStyle() {
        return SOAPNamespaceConstants.ENCODING;
    }
    
    public java.lang.String getImplicitEnvelopeEncodingStyle() {
        return "";
    }
    
    
    /*
     * This method must determine the opcode of the operation given the QName of the first body element.
     */
    public int getOpcodeForFirstBodyElementName(QName name) {
        if (name == null) {
            return InternalSOAPMessage.NO_OPERATION;
        }
        if (name.equals(ns1_cancelTicket_cancelTicket_QNAME)) {
            return cancelTicket_OPCODE;
        }
        if (name.equals(ns1_bookMovieTicket_bookMovieTicket_QNAME)) {
            return bookMovieTicket_OPCODE;
        }
        return super.getOpcodeForFirstBodyElementName(name);
    }
    
    
    private Method internalGetMethodForOpcode(int opcode) throws ClassNotFoundException, NoSuchMethodException {
        
        Method theMethod = null;
        
        switch(opcode) {
            case cancelTicket_OPCODE:
                {
                    Class[] carray = { java.lang.String.class };
                    theMethod = (com.paytm.web.provider.PaytmMovieSIE.class).getMethod("cancelTicket", carray);
                }
                break;
            
            case bookMovieTicket_OPCODE:
                {
                    Class[] carray = { java.lang.String.class,java.lang.String.class };
                    theMethod = (com.paytm.web.provider.PaytmMovieSIE.class).getMethod("bookMovieTicket", carray);
                }
                break;
            
            default:
        }
        return theMethod;
    }
    
    private Method[] methodMap = new Method[2];
    
    /*
     * This method returns the Method Obj for a specified opcode.
     */
    public Method getMethodForOpcode(int opcode) throws ClassNotFoundException, NoSuchMethodException {
         
        if (opcode <= InternalSOAPMessage.NO_OPERATION ) {
            return null;
        }
         
        if (opcode >= 2 ) {
            return null;
        }
         
        if (methodMap[opcode] == null)  {
            methodMap[opcode] = internalGetMethodForOpcode(opcode);
        }
         
        return methodMap[opcode];
    }
    
    /*
     * This method returns an array containing (prefix, nsURI) pairs.
     */
    protected java.lang.String[] getNamespaceDeclarations() {
        return myNamespace_declarations;
    }
    
    /*
     * This method returns an array containing the names of the headers we understand.
     */
    public javax.xml.namespace.QName[] getUnderstoodHeaders() {
        return understoodHeaderNames;
    }
    
    
    protected boolean preHandlingHook(StreamingHandlerState state) throws Exception {
        boolean bool = false;
        bool = super.preHandlingHook(state);
        return bool;
    }
    
    
    protected void postResponseWritingHook(StreamingHandlerState state) throws Exception {
        super.postResponseWritingHook(state);
    }
    
    private void initialize(InternalTypeMappingRegistry registry) throws Exception {
        ns2_myPaytmMovieSIE_cancelTicket_RequestStruct_SOAPSerializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, com.paytm.web.provider.PaytmMovieSIE_cancelTicket_RequestStruct.class, ns2_cancelTicket_TYPE_QNAME);
        ns2_myPaytmMovieSIE_cancelTicket_ResponseStruct_SOAPSerializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, com.paytm.web.provider.PaytmMovieSIE_cancelTicket_ResponseStruct.class, ns2_cancelTicketResponse_TYPE_QNAME);
        ns2_myPaytmMovieSIE_bookMovieTicket_RequestStruct_SOAPSerializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, com.paytm.web.provider.PaytmMovieSIE_bookMovieTicket_RequestStruct.class, ns2_bookMovieTicket_TYPE_QNAME);
        ns2_myPaytmMovieSIE_bookMovieTicket_ResponseStruct_SOAPSerializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, com.paytm.web.provider.PaytmMovieSIE_bookMovieTicket_ResponseStruct.class, ns2_bookMovieTicketResponse_TYPE_QNAME);
    }
    
    private static final javax.xml.namespace.QName portName = new QName("http://paytm.com/partners/service", "PaytmMovieSIE");
    private static final int cancelTicket_OPCODE = 0;
    private static final int bookMovieTicket_OPCODE = 1;
    private static final javax.xml.namespace.QName ns1_cancelTicket_cancelTicket_QNAME = new QName("http://paytm.com/partners/service", "cancelTicket");
    private static final javax.xml.namespace.QName ns2_cancelTicket_TYPE_QNAME = new QName("http://paytm.com/partners/types", "cancelTicket");
    private CombinedSerializer ns2_myPaytmMovieSIE_cancelTicket_RequestStruct_SOAPSerializer;
    private static final javax.xml.namespace.QName ns1_cancelTicket_cancelTicketResponse_QNAME = new QName("http://paytm.com/partners/service", "cancelTicketResponse");
    private static final javax.xml.namespace.QName ns2_cancelTicketResponse_TYPE_QNAME = new QName("http://paytm.com/partners/types", "cancelTicketResponse");
    private CombinedSerializer ns2_myPaytmMovieSIE_cancelTicket_ResponseStruct_SOAPSerializer;
    private static final javax.xml.namespace.QName ns1_bookMovieTicket_bookMovieTicket_QNAME = new QName("http://paytm.com/partners/service", "bookMovieTicket");
    private static final javax.xml.namespace.QName ns2_bookMovieTicket_TYPE_QNAME = new QName("http://paytm.com/partners/types", "bookMovieTicket");
    private CombinedSerializer ns2_myPaytmMovieSIE_bookMovieTicket_RequestStruct_SOAPSerializer;
    private static final javax.xml.namespace.QName ns1_bookMovieTicket_bookMovieTicketResponse_QNAME = new QName("http://paytm.com/partners/service", "bookMovieTicketResponse");
    private static final javax.xml.namespace.QName ns2_bookMovieTicketResponse_TYPE_QNAME = new QName("http://paytm.com/partners/types", "bookMovieTicketResponse");
    private CombinedSerializer ns2_myPaytmMovieSIE_bookMovieTicket_ResponseStruct_SOAPSerializer;
    private static final java.lang.String[] myNamespace_declarations =
                                        new java.lang.String[] {
                                            "ns0", "http://paytm.com/partners/types"
                                        };
    
    private static final QName[] understoodHeaderNames = new QName[] {  };
}
