// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package in.co.irctc.web.provider.pojo;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.util.exception.LocalizableExceptionAdapter;

public class PassengerInfo_SOAPBuilder implements SOAPInstanceBuilder {
    private in.co.irctc.web.provider.pojo.PassengerInfo _instance;
    private int age;
    private java.lang.String name;
    private java.lang.String proofId;
    private static final int myAGE_INDEX = 0;
    private static final int myNAME_INDEX = 1;
    private static final int myPROOFID_INDEX = 2;
    
    public PassengerInfo_SOAPBuilder() {
    }
    
    public void setAge(int age) {
        this.age = age;
    }
    
    public void setName(java.lang.String name) {
        this.name = name;
    }
    
    public void setProofId(java.lang.String proofId) {
        this.proofId = proofId;
    }
    
    public int memberGateType(int memberIndex) {
        switch (memberIndex) {
            case myNAME_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myPROOFID_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            default:
                throw new IllegalArgumentException();
        }
    }
    
    public void construct() {
    }
    
    public void setMember(int index, java.lang.Object memberValue) {
        try {
            switch(index) {
                case myNAME_INDEX:
                    _instance.setName((java.lang.String)memberValue);
                    break;
                case myPROOFID_INDEX:
                    _instance.setProofId((java.lang.String)memberValue);
                    break;
                default:
                    throw new java.lang.IllegalArgumentException();
            }
        }
        catch (java.lang.RuntimeException e) {
            throw e;
        }
        catch (java.lang.Exception e) {
            throw new DeserializationException(new LocalizableExceptionAdapter(e));
        }
    }
    
    public void initialize() {
    }
    
    public void setInstance(java.lang.Object instance) {
        _instance = (in.co.irctc.web.provider.pojo.PassengerInfo)instance;
    }
    
    public java.lang.Object getInstance() {
        return _instance;
    }
}
