// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package in.co.irctc.service.bindings;

import com.sun.xml.rpc.client.BasicService;
import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.simpletype.*;
import com.sun.xml.rpc.encoding.soap.*;
import com.sun.xml.rpc.encoding.literal.*;
import com.sun.xml.rpc.soap.SOAPVersion;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;
import javax.xml.rpc.*;
import javax.xml.rpc.encoding.*;
import javax.xml.namespace.QName;

public class IRCTCService_SerializerRegistry implements SerializerConstants {
    public IRCTCService_SerializerRegistry() {
    }
    
    public TypeMappingRegistry getRegistry() {
        
        TypeMappingRegistry registry = BasicService.createStandardTypeMappingRegistry();
        TypeMapping mapping12 = registry.getTypeMapping(SOAP12Constants.NS_SOAP_ENCODING);
        TypeMapping mapping = registry.getTypeMapping(SOAPConstants.NS_SOAP_ENCODING);
        TypeMapping mapping2 = registry.getTypeMapping("");
        {
            QName type = new QName("http://irctc.co.in/partners/ticketsinfo/types", "JourneyInfo");
            CombinedSerializer serializer = new in.co.irctc.web.provider.JourneyInfo_SOAPSerializer(type,
                ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,in.co.irctc.web.provider.JourneyInfo.class, type, serializer);
        }
        {
            QName type = new QName("http://irctc.co.in/partners/ticketsinfo/types", "bootTicketResponse");
            CombinedSerializer serializer = new in.co.irctc.web.provider.IRCTCServiceSIE_bootTicket_ResponseStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,in.co.irctc.web.provider.IRCTCServiceSIE_bootTicket_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://irctc.co.in/partners/ticketsinfo/types", "bootTicket");
            CombinedSerializer serializer = new in.co.irctc.web.provider.IRCTCServiceSIE_bootTicket_RequestStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,in.co.irctc.web.provider.IRCTCServiceSIE_bootTicket_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://irctc.co.in/partners/ticketsinfo/types", "PassengerInfo");
            CombinedSerializer serializer = new in.co.irctc.web.provider.PassengerInfo_SOAPSerializer(type,
                ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,in.co.irctc.web.provider.PassengerInfo.class, type, serializer);
        }
        {
            QName type = new QName("http://irctc.co.in/partners/ticketsinfo/types", "Ticket");
            CombinedSerializer serializer = new in.co.irctc.web.provider.Ticket_SOAPSerializer(type,
                ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,in.co.irctc.web.provider.Ticket.class, type, serializer);
        }
        {
            QName type = new QName("http://irctc.co.in/partners/ticketsinfo/types", "getTicketPriceResponse");
            CombinedSerializer serializer = new in.co.irctc.web.provider.IRCTCServiceSIE_getTicketPrice_ResponseStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,in.co.irctc.web.provider.IRCTCServiceSIE_getTicketPrice_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://irctc.co.in/partners/ticketsinfo/types", "getTicketPrice");
            CombinedSerializer serializer = new in.co.irctc.web.provider.IRCTCServiceSIE_getTicketPrice_RequestStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,in.co.irctc.web.provider.IRCTCServiceSIE_getTicketPrice_RequestStruct.class, type, serializer);
        }
        return registry;
    }
    
    private static void registerSerializer(TypeMapping mapping, java.lang.Class javaType, javax.xml.namespace.QName xmlType,
        Serializer ser) {
        mapping.register(javaType, xmlType, new SingletonSerializerFactory(ser),
            new SingletonDeserializerFactory((Deserializer)ser));
    }
    
}
