// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.ola.services;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.literal.DetailFragmentDeserializer;
import com.sun.xml.rpc.encoding.simpletype.*;
import com.sun.xml.rpc.encoding.soap.SOAPConstants;
import com.sun.xml.rpc.encoding.soap.SOAP12Constants;
import com.sun.xml.rpc.streaming.*;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;
import javax.xml.namespace.QName;

public class Passenger_SOAPSerializer extends ObjectSerializerBase implements Initializable {
    private static final javax.xml.namespace.QName ns1_passengerId_QNAME = new QName("", "passengerId");
    private static final javax.xml.namespace.QName ns3_string_TYPE_QNAME = SchemaConstants.QNAME_TYPE_STRING;
    private CombinedSerializer ns3_myns3_string__java_lang_String_String_Serializer;
    private static final javax.xml.namespace.QName ns1_passengerName_QNAME = new QName("", "passengerName");
    private static final javax.xml.namespace.QName ns1_passengerMobileNo_QNAME = new QName("", "passengerMobileNo");
    private static final javax.xml.namespace.QName ns1_passengerEmail_QNAME = new QName("", "passengerEmail");
    private static final javax.xml.namespace.QName ns1_noOfPassenger_QNAME = new QName("", "noOfPassenger");
    private static final javax.xml.namespace.QName ns3_int_TYPE_QNAME = SchemaConstants.QNAME_TYPE_INT;
    private CombinedSerializer ns3_myns3__int__int_Int_Serializer;
    private static final int myPASSENGERID_INDEX = 0;
    private static final int myPASSENGERNAME_INDEX = 1;
    private static final int myPASSENGERMOBILENO_INDEX = 2;
    private static final int myPASSENGEREMAIL_INDEX = 3;
    private static final int myNOOFPASSENGER_INDEX = 4;
    
    public Passenger_SOAPSerializer(QName type, boolean encodeType, boolean isNullable, String encodingStyle) {
        super(type, encodeType, isNullable, encodingStyle);
    }
    
    public void initialize(InternalTypeMappingRegistry registry) throws java.lang.Exception {
        ns3_myns3_string__java_lang_String_String_Serializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, java.lang.String.class, ns3_string_TYPE_QNAME);
        ns3_myns3__int__int_Int_Serializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, int.class, ns3_int_TYPE_QNAME);
    }
    
    public java.lang.Object doDeserialize(SOAPDeserializationState state, XMLReader reader,
        SOAPDeserializationContext context) throws java.lang.Exception {
        com.ola.services.Passenger instance = new com.ola.services.Passenger();
        com.ola.services.Passenger_SOAPBuilder builder = null;
        java.lang.Object member;
        boolean isComplete = true;
        javax.xml.namespace.QName elementName;
        
        reader.nextElementContent();
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_passengerId_QNAME)) {
                member = ns3_myns3_string__java_lang_String_String_Serializer.deserialize(ns1_passengerId_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.ola.services.Passenger_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myPASSENGERID_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setPassengerId((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_passengerName_QNAME)) {
                member = ns3_myns3_string__java_lang_String_String_Serializer.deserialize(ns1_passengerName_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.ola.services.Passenger_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myPASSENGERNAME_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setPassengerName((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_passengerMobileNo_QNAME)) {
                member = ns3_myns3_string__java_lang_String_String_Serializer.deserialize(ns1_passengerMobileNo_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.ola.services.Passenger_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myPASSENGERMOBILENO_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setPassengerMobileNo((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_passengerEmail_QNAME)) {
                member = ns3_myns3_string__java_lang_String_String_Serializer.deserialize(ns1_passengerEmail_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.ola.services.Passenger_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myPASSENGEREMAIL_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setPassengerEmail((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_noOfPassenger_QNAME)) {
                member = ns3_myns3__int__int_Int_Serializer.deserialize(ns1_noOfPassenger_QNAME, reader, context);
                instance.setNoOfPassenger(((java.lang.Integer)member).intValue());
                reader.nextElementContent();
            }
        }
        
        XMLReaderUtil.verifyReaderState(reader, XMLReader.END);
        return (isComplete ? (java.lang.Object)instance : (java.lang.Object)state);
    }
    
    public void doSerializeAttributes(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        com.ola.services.Passenger instance = (com.ola.services.Passenger)obj;
        
    }
    
    public void doSerializeInstance(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        com.ola.services.Passenger instance = (com.ola.services.Passenger)obj;
        
        ns3_myns3_string__java_lang_String_String_Serializer.serialize(instance.getPassengerId(), ns1_passengerId_QNAME, null, writer, context);
        ns3_myns3_string__java_lang_String_String_Serializer.serialize(instance.getPassengerName(), ns1_passengerName_QNAME, null, writer, context);
        ns3_myns3_string__java_lang_String_String_Serializer.serialize(instance.getPassengerMobileNo(), ns1_passengerMobileNo_QNAME, null, writer, context);
        ns3_myns3_string__java_lang_String_String_Serializer.serialize(instance.getPassengerEmail(), ns1_passengerEmail_QNAME, null, writer, context);
        ns3_myns3__int__int_Int_Serializer.serialize(new java.lang.Integer(instance.getNoOfPassenger()), ns1_noOfPassenger_QNAME, null, writer, context);
    }
}
