//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.12 at 05:11:40 AM GMT-12:00 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ebay.in/sales/products")
package com.ebaysales.products;
