// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.paytm.web.provider;


public class PaytmMovieSIE_bookMovieTicket_RequestStruct {
    protected java.lang.String String_1;
    protected java.lang.String String_2;
    
    public PaytmMovieSIE_bookMovieTicket_RequestStruct() {
    }
    
    public PaytmMovieSIE_bookMovieTicket_RequestStruct(java.lang.String String_1, java.lang.String String_2) {
        this.String_1 = String_1;
        this.String_2 = String_2;
    }
    
    public java.lang.String getString_1() {
        return String_1;
    }
    
    public void setString_1(java.lang.String String_1) {
        this.String_1 = String_1;
    }
    
    public java.lang.String getString_2() {
        return String_2;
    }
    
    public void setString_2(java.lang.String String_2) {
        this.String_2 = String_2;
    }
}
