// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.irctc.web.provider;

import com.sun.xml.rpc.server.http.MessageContextProperties;
import com.sun.xml.rpc.streaming.*;
import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.soap.SOAPConstants;
import com.sun.xml.rpc.encoding.soap.SOAP12Constants;
import com.sun.xml.rpc.encoding.literal.*;
import com.sun.xml.rpc.soap.streaming.*;
import com.sun.xml.rpc.soap.message.*;
import com.sun.xml.rpc.soap.SOAPVersion;
import com.sun.xml.rpc.soap.SOAPEncodingConstants;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;
import javax.xml.namespace.QName;
import java.rmi.RemoteException;
import java.util.Iterator;
import java.lang.reflect.*;
import java.lang.Class;
import com.sun.xml.rpc.server.*;
import javax.xml.rpc.handler.HandlerInfo;
import com.sun.xml.rpc.client.HandlerChainImpl;

public class IRCTCTicket_Tie
    extends com.sun.xml.rpc.server.TieBase implements SerializerConstants {
    
    
    
    public IRCTCTicket_Tie() throws Exception {
        super(new com.irctc.service.bindings.IRCTCService_SerializerRegistry().getRegistry());
        initialize(internalTypeMappingRegistry);
    }
    
    /*
     * This method does the actual method invocation for operation: bookTicket
     */
    private void invoke_bookTicket(StreamingHandlerState state) throws Exception {
        
        com.irctc.web.provider.IRCTCTicket_bookTicket_RequestStruct myIRCTCTicket_bookTicket_RequestStruct = null;
        Object myIRCTCTicket_bookTicket_RequestStructObj =
            state.getRequest().getBody().getValue();
        
        if (myIRCTCTicket_bookTicket_RequestStructObj instanceof SOAPDeserializationState) {
            myIRCTCTicket_bookTicket_RequestStruct = (com.irctc.web.provider.IRCTCTicket_bookTicket_RequestStruct)((SOAPDeserializationState)myIRCTCTicket_bookTicket_RequestStructObj).getInstance();
        } else {
            myIRCTCTicket_bookTicket_RequestStruct = (com.irctc.web.provider.IRCTCTicket_bookTicket_RequestStruct)myIRCTCTicket_bookTicket_RequestStructObj;
        }
        
        try {
            long result = 
                ((com.irctc.web.provider.IRCTCTicket) getTarget()).bookTicket(myIRCTCTicket_bookTicket_RequestStruct.getJourneyInfo_1(), myIRCTCTicket_bookTicket_RequestStruct.getPassengerInfo_2());
            com.irctc.web.provider.IRCTCTicket_bookTicket_ResponseStruct myIRCTCTicket_bookTicket_ResponseStruct =
                new com.irctc.web.provider.IRCTCTicket_bookTicket_ResponseStruct();
            SOAPHeaderBlockInfo headerInfo;
            myIRCTCTicket_bookTicket_ResponseStruct.setResult(result);
            
            SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_bookTicket_bookTicketResponse_QNAME);
            bodyBlock.setValue(myIRCTCTicket_bookTicket_ResponseStruct);
            bodyBlock.setSerializer(ns2_myIRCTCTicket_bookTicket_ResponseStruct_SOAPSerializer);
            state.getResponse().setBody(bodyBlock);
        } catch (javax.xml.rpc.soap.SOAPFaultException e) {
            SOAPFaultInfo fault = new SOAPFaultInfo(e.getFaultCode(),
                e.getFaultString(), e.getFaultActor(), e.getDetail());
            SOAPBlockInfo faultBlock = new SOAPBlockInfo(com.sun.xml.rpc.encoding.soap.SOAPConstants.QNAME_SOAP_FAULT);
            faultBlock.setValue(fault);
            faultBlock.setSerializer(new SOAPFaultInfoSerializer(false, e.getDetail()==null));
            state.getResponse().setBody(faultBlock);
            state.getResponse().setFailure(true);
        }
    }
    
    /*
     * This method does the actual method invocation for operation: getTicketForBooking
     */
    private void invoke_getTicketForBooking(StreamingHandlerState state) throws Exception {
        
        com.irctc.web.provider.IRCTCTicket_getTicketForBooking_RequestStruct myIRCTCTicket_getTicketForBooking_RequestStruct = null;
        Object myIRCTCTicket_getTicketForBooking_RequestStructObj =
            state.getRequest().getBody().getValue();
        
        if (myIRCTCTicket_getTicketForBooking_RequestStructObj instanceof SOAPDeserializationState) {
            myIRCTCTicket_getTicketForBooking_RequestStruct = (com.irctc.web.provider.IRCTCTicket_getTicketForBooking_RequestStruct)((SOAPDeserializationState)myIRCTCTicket_getTicketForBooking_RequestStructObj).getInstance();
        } else {
            myIRCTCTicket_getTicketForBooking_RequestStruct = (com.irctc.web.provider.IRCTCTicket_getTicketForBooking_RequestStruct)myIRCTCTicket_getTicketForBooking_RequestStructObj;
        }
        
        try {
            com.irctc.web.provider.Ticket result = 
                ((com.irctc.web.provider.IRCTCTicket) getTarget()).getTicketForBooking(myIRCTCTicket_getTicketForBooking_RequestStruct.getJourneyInfo_1(), myIRCTCTicket_getTicketForBooking_RequestStruct.getPassengerInfo_2());
            com.irctc.web.provider.IRCTCTicket_getTicketForBooking_ResponseStruct myIRCTCTicket_getTicketForBooking_ResponseStruct =
                new com.irctc.web.provider.IRCTCTicket_getTicketForBooking_ResponseStruct();
            SOAPHeaderBlockInfo headerInfo;
            myIRCTCTicket_getTicketForBooking_ResponseStruct.setResult(result);
            
            SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_getTicketForBooking_getTicketForBookingResponse_QNAME);
            bodyBlock.setValue(myIRCTCTicket_getTicketForBooking_ResponseStruct);
            bodyBlock.setSerializer(ns2_myIRCTCTicket_getTicketForBooking_ResponseStruct_SOAPSerializer);
            state.getResponse().setBody(bodyBlock);
        } catch (javax.xml.rpc.soap.SOAPFaultException e) {
            SOAPFaultInfo fault = new SOAPFaultInfo(e.getFaultCode(),
                e.getFaultString(), e.getFaultActor(), e.getDetail());
            SOAPBlockInfo faultBlock = new SOAPBlockInfo(com.sun.xml.rpc.encoding.soap.SOAPConstants.QNAME_SOAP_FAULT);
            faultBlock.setValue(fault);
            faultBlock.setSerializer(new SOAPFaultInfoSerializer(false, e.getDetail()==null));
            state.getResponse().setBody(faultBlock);
            state.getResponse().setFailure(true);
        }
    }
    
    /*
     * This method must determine the opcode of the operation that has been invoked.
     */
    protected void peekFirstBodyElement(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingHandlerState state) throws Exception {
        if (bodyReader.getName().equals(ns1_bookTicket_bookTicket_QNAME)) {
            state.getRequest().setOperationCode(bookTicket_OPCODE);
        }
        else if (bodyReader.getName().equals(ns1_getTicketForBooking_getTicketForBooking_QNAME)) {
            state.getRequest().setOperationCode(getTicketForBooking_OPCODE);
        }
        else {
            throw new SOAPProtocolViolationException("soap.operation.unrecognized", bodyReader.getName().toString());
        }
    }
    
    /*
     *  this method deserializes the request/response structure in the body
     */
    protected void readFirstBodyElement(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingHandlerState  state) throws Exception {
        int opcode = state.getRequest().getOperationCode();
        switch (opcode) {
            case bookTicket_OPCODE:
                deserialize_bookTicket(bodyReader, deserializationContext, state);
                break;
            case getTicketForBooking_OPCODE:
                deserialize_getTicketForBooking(bodyReader, deserializationContext, state);
                break;
            default:
                throw new SOAPProtocolViolationException("soap.operation.unrecognized", java.lang.Integer.toString(opcode));
        }
    }
    
    
    
    /*
     * This method deserializes the body of the bookTicket operation.
     */
    private void deserialize_bookTicket(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingHandlerState state) throws Exception {
        java.lang.Object myIRCTCTicket_bookTicket_RequestStructObj =
            ns2_myIRCTCTicket_bookTicket_RequestStruct_SOAPSerializer.deserialize(ns1_bookTicket_bookTicket_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_bookTicket_bookTicket_QNAME);
        bodyBlock.setValue(myIRCTCTicket_bookTicket_RequestStructObj);
        state.getRequest().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the getTicketForBooking operation.
     */
    private void deserialize_getTicketForBooking(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingHandlerState state) throws Exception {
        java.lang.Object myIRCTCTicket_getTicketForBooking_RequestStructObj =
            ns2_myIRCTCTicket_getTicketForBooking_RequestStruct_SOAPSerializer.deserialize(ns1_getTicketForBooking_getTicketForBooking_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_getTicketForBooking_getTicketForBooking_QNAME);
        bodyBlock.setValue(myIRCTCTicket_getTicketForBooking_RequestStructObj);
        state.getRequest().setBody(bodyBlock);
    }
    
    
    /*
     * This method must invoke the correct method on the servant based on the opcode.
     */
    protected void processingHook(StreamingHandlerState state) throws Exception {
        switch (state.getRequest().getOperationCode()) {
            case bookTicket_OPCODE:
                invoke_bookTicket(state);
                break;
            case getTicketForBooking_OPCODE:
                invoke_getTicketForBooking(state);
                break;
            default:
                throw new SOAPProtocolViolationException("soap.operation.unrecognized", java.lang.Integer.toString(state.getRequest().getOperationCode()));
        }
    }
    
    public java.lang.String getDefaultEnvelopeEncodingStyle() {
        return SOAPNamespaceConstants.ENCODING;
    }
    
    public java.lang.String getImplicitEnvelopeEncodingStyle() {
        return "";
    }
    
    
    /*
     * This method must determine the opcode of the operation given the QName of the first body element.
     */
    public int getOpcodeForFirstBodyElementName(QName name) {
        if (name == null) {
            return InternalSOAPMessage.NO_OPERATION;
        }
        if (name.equals(ns1_bookTicket_bookTicket_QNAME)) {
            return bookTicket_OPCODE;
        }
        if (name.equals(ns1_getTicketForBooking_getTicketForBooking_QNAME)) {
            return getTicketForBooking_OPCODE;
        }
        return super.getOpcodeForFirstBodyElementName(name);
    }
    
    
    private Method internalGetMethodForOpcode(int opcode) throws ClassNotFoundException, NoSuchMethodException {
        
        Method theMethod = null;
        
        switch(opcode) {
            case bookTicket_OPCODE:
                {
                    Class[] carray = { com.irctc.web.provider.JourneyInfo.class,com.irctc.web.provider.PassengerInfo.class };
                    theMethod = (com.irctc.web.provider.IRCTCTicket.class).getMethod("bookTicket", carray);
                }
                break;
            
            case getTicketForBooking_OPCODE:
                {
                    Class[] carray = { com.irctc.web.provider.JourneyInfo.class,com.irctc.web.provider.PassengerInfo.class };
                    theMethod = (com.irctc.web.provider.IRCTCTicket.class).getMethod("getTicketForBooking", carray);
                }
                break;
            
            default:
        }
        return theMethod;
    }
    
    private Method[] methodMap = new Method[2];
    
    /*
     * This method returns the Method Obj for a specified opcode.
     */
    public Method getMethodForOpcode(int opcode) throws ClassNotFoundException, NoSuchMethodException {
         
        if (opcode <= InternalSOAPMessage.NO_OPERATION ) {
            return null;
        }
         
        if (opcode >= 2 ) {
            return null;
        }
         
        if (methodMap[opcode] == null)  {
            methodMap[opcode] = internalGetMethodForOpcode(opcode);
        }
         
        return methodMap[opcode];
    }
    
    /*
     * This method returns an array containing (prefix, nsURI) pairs.
     */
    protected java.lang.String[] getNamespaceDeclarations() {
        return myNamespace_declarations;
    }
    
    /*
     * This method returns an array containing the names of the headers we understand.
     */
    public javax.xml.namespace.QName[] getUnderstoodHeaders() {
        return understoodHeaderNames;
    }
    
    
    protected boolean preHandlingHook(StreamingHandlerState state) throws Exception {
        boolean bool = false;
        bool = super.preHandlingHook(state);
        return bool;
    }
    
    
    protected void postResponseWritingHook(StreamingHandlerState state) throws Exception {
        super.postResponseWritingHook(state);
    }
    
    private void initialize(InternalTypeMappingRegistry registry) throws Exception {
        ns2_myIRCTCTicket_bookTicket_ResponseStruct_SOAPSerializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, com.irctc.web.provider.IRCTCTicket_bookTicket_ResponseStruct.class, ns2_bookTicketResponse_TYPE_QNAME);
        ns2_myIRCTCTicket_bookTicket_RequestStruct_SOAPSerializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, com.irctc.web.provider.IRCTCTicket_bookTicket_RequestStruct.class, ns2_bookTicket_TYPE_QNAME);
        ns2_myIRCTCTicket_getTicketForBooking_RequestStruct_SOAPSerializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, com.irctc.web.provider.IRCTCTicket_getTicketForBooking_RequestStruct.class, ns2_getTicketForBooking_TYPE_QNAME);
        ns2_myIRCTCTicket_getTicketForBooking_ResponseStruct_SOAPSerializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, com.irctc.web.provider.IRCTCTicket_getTicketForBooking_ResponseStruct.class, ns2_getTicketForBookingResponse_TYPE_QNAME);
    }
    
    private static final javax.xml.namespace.QName portName = new QName("http://irctc.com/partners/ticketsinfo/service", "IRCTCTicket");
    private static final int bookTicket_OPCODE = 0;
    private static final int getTicketForBooking_OPCODE = 1;
    private static final javax.xml.namespace.QName ns1_bookTicket_bookTicket_QNAME = new QName("http://irctc.com/partners/ticketsinfo/service", "bookTicket");
    private static final javax.xml.namespace.QName ns2_bookTicket_TYPE_QNAME = new QName("http://irctc.com/partners/ticketsinfo/types", "bookTicket");
    private CombinedSerializer ns2_myIRCTCTicket_bookTicket_RequestStruct_SOAPSerializer;
    private static final javax.xml.namespace.QName ns1_bookTicket_bookTicketResponse_QNAME = new QName("http://irctc.com/partners/ticketsinfo/service", "bookTicketResponse");
    private static final javax.xml.namespace.QName ns2_bookTicketResponse_TYPE_QNAME = new QName("http://irctc.com/partners/ticketsinfo/types", "bookTicketResponse");
    private CombinedSerializer ns2_myIRCTCTicket_bookTicket_ResponseStruct_SOAPSerializer;
    private static final javax.xml.namespace.QName ns1_getTicketForBooking_getTicketForBooking_QNAME = new QName("http://irctc.com/partners/ticketsinfo/service", "getTicketForBooking");
    private static final javax.xml.namespace.QName ns2_getTicketForBooking_TYPE_QNAME = new QName("http://irctc.com/partners/ticketsinfo/types", "getTicketForBooking");
    private CombinedSerializer ns2_myIRCTCTicket_getTicketForBooking_RequestStruct_SOAPSerializer;
    private static final javax.xml.namespace.QName ns1_getTicketForBooking_getTicketForBookingResponse_QNAME = new QName("http://irctc.com/partners/ticketsinfo/service", "getTicketForBookingResponse");
    private static final javax.xml.namespace.QName ns2_getTicketForBookingResponse_TYPE_QNAME = new QName("http://irctc.com/partners/ticketsinfo/types", "getTicketForBookingResponse");
    private CombinedSerializer ns2_myIRCTCTicket_getTicketForBooking_ResponseStruct_SOAPSerializer;
    private static final java.lang.String[] myNamespace_declarations =
                                        new java.lang.String[] {
                                            "ns0", "http://irctc.com/partners/ticketsinfo/types"
                                        };
    
    private static final QName[] understoodHeaderNames = new QName[] {  };
}
