
package org.upi.upipayments2.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.upi.upipayments2.service.UpiPayment;
import org.upi.upipayments2.types.Reciept;
import org.upi.upipayments2.types.UpiAccount;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0-b26-ea3
 * Generated source version: 2.0
 * 
 */
@WebService(name = "upiPayment", targetNamespace = "http://www.upi.org/upiPayments2/service", wsdlLocation = "http://localhost:8080/UPIPayments2/upiPay?wsdl")
public interface UpiPayment {


    /**
     * 
     * @param amount
     * @param fromAccount
     * @param toAccount
     * @return
     *     returns org.upi.upipayments2.types.Reciept
     */
    @WebMethod(action = "http://www.npci.org.in/digitalPayment/service/sendMoney")
    @WebResult(name = "reciept", targetNamespace = "http://www.upi.org/upiPayments2/types")
    @RequestWrapper(localName = "sendMoney", targetNamespace = "http://www.upi.org/upiPayments2/types", className = "org.upi.upipayments2.types.SendMoney")
    @ResponseWrapper(localName = "sendMoneyResponse", targetNamespace = "http://www.upi.org/upiPayments2/types", className = "org.upi.upipayments2.types.SendMoneyResponse")
    public Reciept sendMoney(
        @WebParam(name = "from-account", targetNamespace = "http://www.upi.org/upiPayments2/types")
        UpiAccount fromAccount,
        @WebParam(name = "to-account", targetNamespace = "http://www.upi.org/upiPayments2/types")
        UpiAccount toAccount,
        @WebParam(name = "amount", targetNamespace = "http://www.upi.org/upiPayments2/types")
        Double amount);

}
