// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.ola.services;

import com.sun.xml.rpc.server.http.MessageContextProperties;
import com.sun.xml.rpc.streaming.*;
import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.soap.SOAPConstants;
import com.sun.xml.rpc.encoding.soap.SOAP12Constants;
import com.sun.xml.rpc.encoding.literal.*;
import com.sun.xml.rpc.soap.streaming.*;
import com.sun.xml.rpc.soap.message.*;
import com.sun.xml.rpc.soap.SOAPVersion;
import com.sun.xml.rpc.soap.SOAPEncodingConstants;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;
import javax.xml.namespace.QName;
import java.rmi.RemoteException;
import java.util.Iterator;
import java.lang.reflect.*;
import java.lang.Class;
import com.sun.xml.rpc.server.*;
import javax.xml.rpc.handler.HandlerInfo;
import com.sun.xml.rpc.client.HandlerChainImpl;

public class Ola_PortType_Tie
    extends com.sun.xml.rpc.server.TieBase implements SerializerConstants {
    
    
    
    public Ola_PortType_Tie() throws Exception {
        super(new com.ola.services.Ola_Service_SerializerRegistry().getRegistry());
        initialize(internalTypeMappingRegistry);
    }
    
    /*
     * This method does the actual method invocation for operation: bookRide
     */
    private void invoke_bookRide(StreamingHandlerState state) throws Exception {
        
        com.ola.services.Ola_bookRide_RequestStruct2 myOla_bookRide_RequestStruct2 = null;
        Object myOla_bookRide_RequestStruct2Obj =
            state.getRequest().getBody().getValue();
        
        if (myOla_bookRide_RequestStruct2Obj instanceof SOAPDeserializationState) {
            myOla_bookRide_RequestStruct2 = (com.ola.services.Ola_bookRide_RequestStruct2)((SOAPDeserializationState)myOla_bookRide_RequestStruct2Obj).getInstance();
        } else {
            myOla_bookRide_RequestStruct2 = (com.ola.services.Ola_bookRide_RequestStruct2)myOla_bookRide_RequestStruct2Obj;
        }
        
        try {
            com.ola.services.RideDetails result = 
                ((com.ola.services.Ola_PortType) getTarget()).bookRide(myOla_bookRide_RequestStruct2.getTrip(), myOla_bookRide_RequestStruct2.getPassenger());
            com.ola.services.Ola_bookRide_ResponseStruct2 myOla_bookRide_ResponseStruct2 =
                new com.ola.services.Ola_bookRide_ResponseStruct2();
            SOAPHeaderBlockInfo headerInfo;
            myOla_bookRide_ResponseStruct2.setResult(result);
            
            SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_bookRide_bookRideResponse_QNAME);
            bodyBlock.setValue(myOla_bookRide_ResponseStruct2);
            bodyBlock.setSerializer(ns1_myOla_bookRide_ResponseStruct2_SOAPSerializer);
            state.getResponse().setBody(bodyBlock);
        } catch (javax.xml.rpc.soap.SOAPFaultException e) {
            SOAPFaultInfo fault = new SOAPFaultInfo(e.getFaultCode(),
                e.getFaultString(), e.getFaultActor(), e.getDetail());
            SOAPBlockInfo faultBlock = new SOAPBlockInfo(com.sun.xml.rpc.encoding.soap.SOAPConstants.QNAME_SOAP_FAULT);
            faultBlock.setValue(fault);
            faultBlock.setSerializer(new SOAPFaultInfoSerializer(false, e.getDetail()==null));
            state.getResponse().setBody(faultBlock);
            state.getResponse().setFailure(true);
        }
    }
    
    /*
     * This method must determine the opcode of the operation that has been invoked.
     */
    protected void peekFirstBodyElement(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingHandlerState state) throws Exception {
        if (bodyReader.getName().equals(ns1_bookRide_bookRide_QNAME)) {
            state.getRequest().setOperationCode(bookRide_OPCODE);
        }
        else {
            throw new SOAPProtocolViolationException("soap.operation.unrecognized", bodyReader.getName().toString());
        }
    }
    
    /*
     *  this method deserializes the request/response structure in the body
     */
    protected void readFirstBodyElement(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingHandlerState  state) throws Exception {
        int opcode = state.getRequest().getOperationCode();
        switch (opcode) {
            case bookRide_OPCODE:
                deserialize_bookRide(bodyReader, deserializationContext, state);
                break;
            default:
                throw new SOAPProtocolViolationException("soap.operation.unrecognized", java.lang.Integer.toString(opcode));
        }
    }
    
    
    
    /*
     * This method deserializes the body of the bookRide operation.
     */
    private void deserialize_bookRide(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingHandlerState state) throws Exception {
        java.lang.Object myOla_bookRide_RequestStruct2Obj =
            ns1_myOla_bookRide_RequestStruct2_SOAPSerializer.deserialize(ns1_bookRide_bookRide_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_bookRide_bookRide_QNAME);
        bodyBlock.setValue(myOla_bookRide_RequestStruct2Obj);
        state.getRequest().setBody(bodyBlock);
    }
    
    
    /*
     * This method must invoke the correct method on the servant based on the opcode.
     */
    protected void processingHook(StreamingHandlerState state) throws Exception {
        switch (state.getRequest().getOperationCode()) {
            case bookRide_OPCODE:
                invoke_bookRide(state);
                break;
            default:
                throw new SOAPProtocolViolationException("soap.operation.unrecognized", java.lang.Integer.toString(state.getRequest().getOperationCode()));
        }
    }
    
    public java.lang.String getDefaultEnvelopeEncodingStyle() {
        return SOAPNamespaceConstants.ENCODING;
    }
    
    public java.lang.String getImplicitEnvelopeEncodingStyle() {
        return "";
    }
    
    
    /*
     * This method must determine the opcode of the operation given the QName of the first body element.
     */
    public int getOpcodeForFirstBodyElementName(QName name) {
        if (name == null) {
            return InternalSOAPMessage.NO_OPERATION;
        }
        if (name.equals(ns1_bookRide_bookRide_QNAME)) {
            return bookRide_OPCODE;
        }
        return super.getOpcodeForFirstBodyElementName(name);
    }
    
    
    private Method internalGetMethodForOpcode(int opcode) throws ClassNotFoundException, NoSuchMethodException {
        
        Method theMethod = null;
        
        switch(opcode) {
            case bookRide_OPCODE:
                {
                    Class[] carray = { com.ola.services.Trip.class,com.ola.services.Passenger.class };
                    theMethod = (com.ola.services.Ola_PortType.class).getMethod("bookRide", carray);
                }
                break;
            
            default:
        }
        return theMethod;
    }
    
    private Method[] methodMap = new Method[1];
    
    /*
     * This method returns the Method Obj for a specified opcode.
     */
    public Method getMethodForOpcode(int opcode) throws ClassNotFoundException, NoSuchMethodException {
         
        if (opcode <= InternalSOAPMessage.NO_OPERATION ) {
            return null;
        }
         
        if (opcode >= 1 ) {
            return null;
        }
         
        if (methodMap[opcode] == null)  {
            methodMap[opcode] = internalGetMethodForOpcode(opcode);
        }
         
        return methodMap[opcode];
    }
    
    /*
     * This method returns an array containing (prefix, nsURI) pairs.
     */
    protected java.lang.String[] getNamespaceDeclarations() {
        return myNamespace_declarations;
    }
    
    /*
     * This method returns an array containing the names of the headers we understand.
     */
    public javax.xml.namespace.QName[] getUnderstoodHeaders() {
        return understoodHeaderNames;
    }
    
    
    protected boolean preHandlingHook(StreamingHandlerState state) throws Exception {
        boolean bool = false;
        bool = super.preHandlingHook(state);
        return bool;
    }
    
    
    protected void postResponseWritingHook(StreamingHandlerState state) throws Exception {
        super.postResponseWritingHook(state);
    }
    
    private void initialize(InternalTypeMappingRegistry registry) throws Exception {
        ns1_myOla_bookRide_ResponseStruct2_SOAPSerializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, com.ola.services.Ola_bookRide_ResponseStruct2.class, ns1_bookRideResponse_TYPE_QNAME);
        ns1_myOla_bookRide_RequestStruct2_SOAPSerializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, com.ola.services.Ola_bookRide_RequestStruct2.class, ns1_bookRide_TYPE_QNAME);
    }
    
    private static final javax.xml.namespace.QName portName = new QName("http://ola.com/cabs/services", "olaSOAPPort");
    private static final int bookRide_OPCODE = 0;
    private static final javax.xml.namespace.QName ns1_bookRide_bookRide_QNAME = new QName("http://ola.com/cabs/services", "bookRide");
    private static final javax.xml.namespace.QName ns1_bookRide_TYPE_QNAME = new QName("http://ola.com/cabs/services", "bookRide");
    private CombinedSerializer ns1_myOla_bookRide_RequestStruct2_SOAPSerializer;
    private static final javax.xml.namespace.QName ns1_bookRide_bookRideResponse_QNAME = new QName("http://ola.com/cabs/services", "bookRideResponse");
    private static final javax.xml.namespace.QName ns1_bookRideResponse_TYPE_QNAME = new QName("http://ola.com/cabs/services", "bookRideResponse");
    private CombinedSerializer ns1_myOla_bookRide_ResponseStruct2_SOAPSerializer;
    private static final java.lang.String[] myNamespace_declarations =
                                        new java.lang.String[] {
                                            "ns0", "http://ola.com/cabs/services",
                                            "ns1", "http://ola.com/cabs/types"
                                        };
    
    private static final QName[] understoodHeaderNames = new QName[] {  };
}
