// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.ola.services;


public class Ola_bookRide_ResponseStruct2 {
    protected com.ola.services.RideDetails result;
    
    public Ola_bookRide_ResponseStruct2() {
    }
    
    public Ola_bookRide_ResponseStruct2(com.ola.services.RideDetails result) {
        this.result = result;
    }
    
    public com.ola.services.RideDetails getResult() {
        return result;
    }
    
    public void setResult(com.ola.services.RideDetails result) {
        this.result = result;
    }
}
