// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.ola.services;


public class Passenger {
    protected java.lang.String passengerId;
    protected java.lang.String passengerName;
    protected java.lang.String passengerMobileNo;
    protected java.lang.String passengerEmail;
    protected int noOfPassenger;
    
    public Passenger() {
    }
    
    public Passenger(java.lang.String passengerId, java.lang.String passengerName, java.lang.String passengerMobileNo, java.lang.String passengerEmail, int noOfPassenger) {
        this.passengerId = passengerId;
        this.passengerName = passengerName;
        this.passengerMobileNo = passengerMobileNo;
        this.passengerEmail = passengerEmail;
        this.noOfPassenger = noOfPassenger;
    }
    
    public java.lang.String getPassengerId() {
        return passengerId;
    }
    
    public void setPassengerId(java.lang.String passengerId) {
        this.passengerId = passengerId;
    }
    
    public java.lang.String getPassengerName() {
        return passengerName;
    }
    
    public void setPassengerName(java.lang.String passengerName) {
        this.passengerName = passengerName;
    }
    
    public java.lang.String getPassengerMobileNo() {
        return passengerMobileNo;
    }
    
    public void setPassengerMobileNo(java.lang.String passengerMobileNo) {
        this.passengerMobileNo = passengerMobileNo;
    }
    
    public java.lang.String getPassengerEmail() {
        return passengerEmail;
    }
    
    public void setPassengerEmail(java.lang.String passengerEmail) {
        this.passengerEmail = passengerEmail;
    }
    
    public int getNoOfPassenger() {
        return noOfPassenger;
    }
    
    public void setNoOfPassenger(int noOfPassenger) {
        this.noOfPassenger = noOfPassenger;
    }
}
