// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.paytm.web.provider.recharge;


public class PaytmRechargeSIE_recharge2_RequestStruct {
    protected long long_1;
    protected java.lang.String String_2;
    protected java.lang.String String_3;
    
    public PaytmRechargeSIE_recharge2_RequestStruct() {
    }
    
    public PaytmRechargeSIE_recharge2_RequestStruct(long long_1, java.lang.String String_2, java.lang.String String_3) {
        this.long_1 = long_1;
        this.String_2 = String_2;
        this.String_3 = String_3;
    }
    
    public long getLong_1() {
        return long_1;
    }
    
    public void setLong_1(long long_1) {
        this.long_1 = long_1;
    }
    
    public java.lang.String getString_2() {
        return String_2;
    }
    
    public void setString_2(java.lang.String String_2) {
        this.String_2 = String_2;
    }
    
    public java.lang.String getString_3() {
        return String_3;
    }
    
    public void setString_3(java.lang.String String_3) {
        this.String_3 = String_3;
    }
}
