// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.paytm.web.provider.recharge;

import com.sun.xml.rpc.server.http.MessageContextProperties;
import com.sun.xml.rpc.streaming.*;
import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.soap.SOAPConstants;
import com.sun.xml.rpc.encoding.soap.SOAP12Constants;
import com.sun.xml.rpc.encoding.literal.*;
import com.sun.xml.rpc.soap.streaming.*;
import com.sun.xml.rpc.soap.message.*;
import com.sun.xml.rpc.soap.SOAPVersion;
import com.sun.xml.rpc.soap.SOAPEncodingConstants;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;
import javax.xml.namespace.QName;
import java.rmi.RemoteException;
import java.util.Iterator;
import java.lang.reflect.*;
import java.lang.Class;
import com.sun.xml.rpc.server.*;
import javax.xml.rpc.handler.HandlerInfo;
import com.sun.xml.rpc.client.HandlerChainImpl;

public class PaytmRechargeSIE_Tie
    extends com.sun.xml.rpc.server.TieBase implements SerializerConstants {
    
    
    
    public PaytmRechargeSIE_Tie() throws Exception {
        super(new com.paytm.service.bindings.PaytmService_SerializerRegistry().getRegistry());
        initialize(internalTypeMappingRegistry);
    }
    
    /*
     * This method does the actual method invocation for operation: recharge2
     */
    private void invoke_recharge2(StreamingHandlerState state) throws Exception {
        
        com.paytm.web.provider.recharge.PaytmRechargeSIE_recharge2_RequestStruct myPaytmRechargeSIE_recharge2_RequestStruct = null;
        Object myPaytmRechargeSIE_recharge2_RequestStructObj =
            state.getRequest().getBody().getValue();
        
        if (myPaytmRechargeSIE_recharge2_RequestStructObj instanceof SOAPDeserializationState) {
            myPaytmRechargeSIE_recharge2_RequestStruct = (com.paytm.web.provider.recharge.PaytmRechargeSIE_recharge2_RequestStruct)((SOAPDeserializationState)myPaytmRechargeSIE_recharge2_RequestStructObj).getInstance();
        } else {
            myPaytmRechargeSIE_recharge2_RequestStruct = (com.paytm.web.provider.recharge.PaytmRechargeSIE_recharge2_RequestStruct)myPaytmRechargeSIE_recharge2_RequestStructObj;
        }
        
        try {
            java.util.List result = 
                ((com.paytm.web.provider.recharge.PaytmRechargeSIE) getTarget()).recharge(myPaytmRechargeSIE_recharge2_RequestStruct.getLong_1(), myPaytmRechargeSIE_recharge2_RequestStruct.getString_2(), myPaytmRechargeSIE_recharge2_RequestStruct.getString_3());
            com.paytm.web.provider.recharge.PaytmRechargeSIE_recharge_ResponseStruct1 myPaytmRechargeSIE_recharge_ResponseStruct1 =
                new com.paytm.web.provider.recharge.PaytmRechargeSIE_recharge_ResponseStruct1();
            SOAPHeaderBlockInfo headerInfo;
            myPaytmRechargeSIE_recharge_ResponseStruct1.setResult(result);
            
            SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_recharge2_recharge2Response_QNAME);
            bodyBlock.setValue(myPaytmRechargeSIE_recharge_ResponseStruct1);
            bodyBlock.setSerializer(ns2_myPaytmRechargeSIE_recharge_ResponseStruct1_SOAPSerializer);
            state.getResponse().setBody(bodyBlock);
        } catch (javax.xml.rpc.soap.SOAPFaultException e) {
            SOAPFaultInfo fault = new SOAPFaultInfo(e.getFaultCode(),
                e.getFaultString(), e.getFaultActor(), e.getDetail());
            SOAPBlockInfo faultBlock = new SOAPBlockInfo(com.sun.xml.rpc.encoding.soap.SOAPConstants.QNAME_SOAP_FAULT);
            faultBlock.setValue(fault);
            faultBlock.setSerializer(new SOAPFaultInfoSerializer(false, e.getDetail()==null));
            state.getResponse().setBody(faultBlock);
            state.getResponse().setFailure(true);
        }
    }
    
    /*
     * This method does the actual method invocation for operation: recharge
     */
    private void invoke_recharge(StreamingHandlerState state) throws Exception {
        
        com.paytm.web.provider.recharge.PaytmRechargeSIE_recharge_RequestStruct myPaytmRechargeSIE_recharge_RequestStruct = null;
        Object myPaytmRechargeSIE_recharge_RequestStructObj =
            state.getRequest().getBody().getValue();
        
        if (myPaytmRechargeSIE_recharge_RequestStructObj instanceof SOAPDeserializationState) {
            myPaytmRechargeSIE_recharge_RequestStruct = (com.paytm.web.provider.recharge.PaytmRechargeSIE_recharge_RequestStruct)((SOAPDeserializationState)myPaytmRechargeSIE_recharge_RequestStructObj).getInstance();
        } else {
            myPaytmRechargeSIE_recharge_RequestStruct = (com.paytm.web.provider.recharge.PaytmRechargeSIE_recharge_RequestStruct)myPaytmRechargeSIE_recharge_RequestStructObj;
        }
        
        try {
            java.lang.String result = 
                ((com.paytm.web.provider.recharge.PaytmRechargeSIE) getTarget()).recharge(myPaytmRechargeSIE_recharge_RequestStruct.getLong_1());
            com.paytm.web.provider.recharge.PaytmRechargeSIE_recharge_ResponseStruct myPaytmRechargeSIE_recharge_ResponseStruct =
                new com.paytm.web.provider.recharge.PaytmRechargeSIE_recharge_ResponseStruct();
            SOAPHeaderBlockInfo headerInfo;
            myPaytmRechargeSIE_recharge_ResponseStruct.setResult(result);
            
            SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_recharge_rechargeResponse_QNAME);
            bodyBlock.setValue(myPaytmRechargeSIE_recharge_ResponseStruct);
            bodyBlock.setSerializer(ns2_myPaytmRechargeSIE_recharge_ResponseStruct_SOAPSerializer);
            state.getResponse().setBody(bodyBlock);
        } catch (javax.xml.rpc.soap.SOAPFaultException e) {
            SOAPFaultInfo fault = new SOAPFaultInfo(e.getFaultCode(),
                e.getFaultString(), e.getFaultActor(), e.getDetail());
            SOAPBlockInfo faultBlock = new SOAPBlockInfo(com.sun.xml.rpc.encoding.soap.SOAPConstants.QNAME_SOAP_FAULT);
            faultBlock.setValue(fault);
            faultBlock.setSerializer(new SOAPFaultInfoSerializer(false, e.getDetail()==null));
            state.getResponse().setBody(faultBlock);
            state.getResponse().setFailure(true);
        }
    }
    
    /*
     * This method must determine the opcode of the operation that has been invoked.
     */
    protected void peekFirstBodyElement(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingHandlerState state) throws Exception {
        if (bodyReader.getName().equals(ns1_recharge2_recharge2_QNAME)) {
            state.getRequest().setOperationCode(recharge2_OPCODE);
        }
        else if (bodyReader.getName().equals(ns1_recharge_recharge_QNAME)) {
            state.getRequest().setOperationCode(recharge_OPCODE);
        }
        else {
            throw new SOAPProtocolViolationException("soap.operation.unrecognized", bodyReader.getName().toString());
        }
    }
    
    /*
     *  this method deserializes the request/response structure in the body
     */
    protected void readFirstBodyElement(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingHandlerState  state) throws Exception {
        int opcode = state.getRequest().getOperationCode();
        switch (opcode) {
            case recharge2_OPCODE:
                deserialize_recharge2(bodyReader, deserializationContext, state);
                break;
            case recharge_OPCODE:
                deserialize_recharge(bodyReader, deserializationContext, state);
                break;
            default:
                throw new SOAPProtocolViolationException("soap.operation.unrecognized", java.lang.Integer.toString(opcode));
        }
    }
    
    
    
    /*
     * This method deserializes the body of the recharge2 operation.
     */
    private void deserialize_recharge2(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingHandlerState state) throws Exception {
        java.lang.Object myPaytmRechargeSIE_recharge2_RequestStructObj =
            ns2_myPaytmRechargeSIE_recharge2_RequestStruct_SOAPSerializer.deserialize(ns1_recharge2_recharge2_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_recharge2_recharge2_QNAME);
        bodyBlock.setValue(myPaytmRechargeSIE_recharge2_RequestStructObj);
        state.getRequest().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the recharge operation.
     */
    private void deserialize_recharge(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingHandlerState state) throws Exception {
        java.lang.Object myPaytmRechargeSIE_recharge_RequestStructObj =
            ns2_myPaytmRechargeSIE_recharge_RequestStruct_SOAPSerializer.deserialize(ns1_recharge_recharge_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_recharge_recharge_QNAME);
        bodyBlock.setValue(myPaytmRechargeSIE_recharge_RequestStructObj);
        state.getRequest().setBody(bodyBlock);
    }
    
    
    /*
     * This method must invoke the correct method on the servant based on the opcode.
     */
    protected void processingHook(StreamingHandlerState state) throws Exception {
        switch (state.getRequest().getOperationCode()) {
            case recharge2_OPCODE:
                invoke_recharge2(state);
                break;
            case recharge_OPCODE:
                invoke_recharge(state);
                break;
            default:
                throw new SOAPProtocolViolationException("soap.operation.unrecognized", java.lang.Integer.toString(state.getRequest().getOperationCode()));
        }
    }
    
    public java.lang.String getDefaultEnvelopeEncodingStyle() {
        return SOAPNamespaceConstants.ENCODING;
    }
    
    public java.lang.String getImplicitEnvelopeEncodingStyle() {
        return "";
    }
    
    
    /*
     * This method must determine the opcode of the operation given the QName of the first body element.
     */
    public int getOpcodeForFirstBodyElementName(QName name) {
        if (name == null) {
            return InternalSOAPMessage.NO_OPERATION;
        }
        if (name.equals(ns1_recharge2_recharge2_QNAME)) {
            return recharge2_OPCODE;
        }
        if (name.equals(ns1_recharge_recharge_QNAME)) {
            return recharge_OPCODE;
        }
        return super.getOpcodeForFirstBodyElementName(name);
    }
    
    
    private Method internalGetMethodForOpcode(int opcode) throws ClassNotFoundException, NoSuchMethodException {
        
        Method theMethod = null;
        
        switch(opcode) {
            case recharge2_OPCODE:
                {
                    Class[] carray = { Long.TYPE,java.lang.String.class,java.lang.String.class };
                    theMethod = (com.paytm.web.provider.recharge.PaytmRechargeSIE.class).getMethod("recharge", carray);
                }
                break;
            
            case recharge_OPCODE:
                {
                    Class[] carray = { Long.TYPE };
                    theMethod = (com.paytm.web.provider.recharge.PaytmRechargeSIE.class).getMethod("recharge", carray);
                }
                break;
            
            default:
        }
        return theMethod;
    }
    
    private Method[] methodMap = new Method[2];
    
    /*
     * This method returns the Method Obj for a specified opcode.
     */
    public Method getMethodForOpcode(int opcode) throws ClassNotFoundException, NoSuchMethodException {
         
        if (opcode <= InternalSOAPMessage.NO_OPERATION ) {
            return null;
        }
         
        if (opcode >= 2 ) {
            return null;
        }
         
        if (methodMap[opcode] == null)  {
            methodMap[opcode] = internalGetMethodForOpcode(opcode);
        }
         
        return methodMap[opcode];
    }
    
    /*
     * This method returns an array containing (prefix, nsURI) pairs.
     */
    protected java.lang.String[] getNamespaceDeclarations() {
        return myNamespace_declarations;
    }
    
    /*
     * This method returns an array containing the names of the headers we understand.
     */
    public javax.xml.namespace.QName[] getUnderstoodHeaders() {
        return understoodHeaderNames;
    }
    
    
    protected boolean preHandlingHook(StreamingHandlerState state) throws Exception {
        boolean bool = false;
        bool = super.preHandlingHook(state);
        return bool;
    }
    
    
    protected void postResponseWritingHook(StreamingHandlerState state) throws Exception {
        super.postResponseWritingHook(state);
    }
    
    private void initialize(InternalTypeMappingRegistry registry) throws Exception {
        ns2_myPaytmRechargeSIE_recharge2_RequestStruct_SOAPSerializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, com.paytm.web.provider.recharge.PaytmRechargeSIE_recharge2_RequestStruct.class, ns2_recharge2_TYPE_QNAME);
        ns2_myPaytmRechargeSIE_recharge_ResponseStruct1_SOAPSerializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, com.paytm.web.provider.recharge.PaytmRechargeSIE_recharge_ResponseStruct1.class, ns2_recharge2Response_TYPE_QNAME);
        ns2_myPaytmRechargeSIE_recharge_RequestStruct_SOAPSerializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, com.paytm.web.provider.recharge.PaytmRechargeSIE_recharge_RequestStruct.class, ns2_recharge_TYPE_QNAME);
        ns2_myPaytmRechargeSIE_recharge_ResponseStruct_SOAPSerializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, com.paytm.web.provider.recharge.PaytmRechargeSIE_recharge_ResponseStruct.class, ns2_rechargeResponse_TYPE_QNAME);
    }
    
    private static final javax.xml.namespace.QName portName = new QName("http://paytm.com/partners/service", "PaytmRechargeSIE");
    private static final int recharge2_OPCODE = 0;
    private static final int recharge_OPCODE = 1;
    private static final javax.xml.namespace.QName ns1_recharge2_recharge2_QNAME = new QName("http://paytm.com/partners/service", "recharge2");
    private static final javax.xml.namespace.QName ns2_recharge2_TYPE_QNAME = new QName("http://paytm.com/partners/types", "recharge2");
    private CombinedSerializer ns2_myPaytmRechargeSIE_recharge2_RequestStruct_SOAPSerializer;
    private static final javax.xml.namespace.QName ns1_recharge2_recharge2Response_QNAME = new QName("http://paytm.com/partners/service", "recharge2Response");
    private static final javax.xml.namespace.QName ns2_recharge2Response_TYPE_QNAME = new QName("http://paytm.com/partners/types", "recharge2Response");
    private CombinedSerializer ns2_myPaytmRechargeSIE_recharge_ResponseStruct1_SOAPSerializer;
    private static final javax.xml.namespace.QName ns1_recharge_recharge_QNAME = new QName("http://paytm.com/partners/service", "recharge");
    private static final javax.xml.namespace.QName ns2_recharge_TYPE_QNAME = new QName("http://paytm.com/partners/types", "recharge");
    private CombinedSerializer ns2_myPaytmRechargeSIE_recharge_RequestStruct_SOAPSerializer;
    private static final javax.xml.namespace.QName ns1_recharge_rechargeResponse_QNAME = new QName("http://paytm.com/partners/service", "rechargeResponse");
    private static final javax.xml.namespace.QName ns2_rechargeResponse_TYPE_QNAME = new QName("http://paytm.com/partners/types", "rechargeResponse");
    private CombinedSerializer ns2_myPaytmRechargeSIE_recharge_ResponseStruct_SOAPSerializer;
    private static final java.lang.String[] myNamespace_declarations =
                                        new java.lang.String[] {
                                            "ns0", "http://paytm.com/partners/types",
                                            "ns1", "http://java.sun.com/jax-rpc-ri/internal"
                                        };
    
    private static final QName[] understoodHeaderNames = new QName[] {  };
}
