
package org.upi.upipayments2.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import org.upi.upipayments2.service.UpiPayment;
import org.upi.upipayments2.service.UpiPayment_Service;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0-b26-ea3
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "upiPayment", targetNamespace = "http://www.upi.org/upiPayments2/service", wsdlLocation = "WebContent\\WEB-INF\\upiPayments2.wsdl")
public class UpiPayment_Service
    extends Service
{

    private final static URL WSDL_LOCATION;
    private final static QName UPIPAYMENT = new QName("http://www.upi.org/upiPayments2/service", "upiPayment");
    private final static QName UPIPAYMENTSOAPPORT = new QName("http://www.upi.org/upiPayments2/service", "upiPaymentSOAPPort");

    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Others/WS_Workspace/UPIPayments2/WebContent/WEB-INF/upiPayments2.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public UpiPayment_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UpiPayment_Service() {
        super(WSDL_LOCATION, UPIPAYMENT);
    }

    /**
     * 
     * @return
     *     returns UpiPayment
     */
    @WebEndpoint(name = "upiPaymentSOAPPort")
    public UpiPayment getUpiPaymentSOAPPort() {
        return (UpiPayment)super.getPort(UPIPAYMENTSOAPPORT, UpiPayment.class);
    }

}
