// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.irctc.web.provider;


public class IRCTCTicket_getTicketForPnr_RequestStruct {
    protected long long_1;
    
    public IRCTCTicket_getTicketForPnr_RequestStruct() {
    }
    
    public IRCTCTicket_getTicketForPnr_RequestStruct(long long_1) {
        this.long_1 = long_1;
    }
    
    public long getLong_1() {
        return long_1;
    }
    
    public void setLong_1(long long_1) {
        this.long_1 = long_1;
    }
}
