// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.irctc.web.provider;


public class IRCTCTicket_bookTicket_ResponseStruct {
    protected long result;
    
    public IRCTCTicket_bookTicket_ResponseStruct() {
    }
    
    public IRCTCTicket_bookTicket_ResponseStruct(long result) {
        this.result = result;
    }
    
    public long getResult() {
        return result;
    }
    
    public void setResult(long result) {
        this.result = result;
    }
}
