// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.irctc.web.provider;


public class IRCTCTicket_getTicketForPnr_ResponseStruct {
    protected com.irctc.web.provider.Ticket result;
    
    public IRCTCTicket_getTicketForPnr_ResponseStruct() {
    }
    
    public IRCTCTicket_getTicketForPnr_ResponseStruct(com.irctc.web.provider.Ticket result) {
        this.result = result;
    }
    
    public com.irctc.web.provider.Ticket getResult() {
        return result;
    }
    
    public void setResult(com.irctc.web.provider.Ticket result) {
        this.result = result;
    }
}
