// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.irctc.web.provider;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.util.exception.LocalizableExceptionAdapter;

public class IRCTCTicket_bookTicket_RequestStruct_SOAPBuilder implements SOAPInstanceBuilder {
    private com.irctc.web.provider.IRCTCTicket_bookTicket_RequestStruct _instance;
    private com.irctc.web.provider.JourneyInfo JourneyInfo_1;
    private com.irctc.web.provider.PassengerInfo PassengerInfo_2;
    private static final int myJOURNEYINFO_1_INDEX = 0;
    private static final int myPASSENGERINFO_2_INDEX = 1;
    
    public IRCTCTicket_bookTicket_RequestStruct_SOAPBuilder() {
    }
    
    public void setJourneyInfo_1(com.irctc.web.provider.JourneyInfo JourneyInfo_1) {
        this.JourneyInfo_1 = JourneyInfo_1;
    }
    
    public void setPassengerInfo_2(com.irctc.web.provider.PassengerInfo PassengerInfo_2) {
        this.PassengerInfo_2 = PassengerInfo_2;
    }
    
    public int memberGateType(int memberIndex) {
        switch (memberIndex) {
            case myJOURNEYINFO_1_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myPASSENGERINFO_2_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            default:
                throw new IllegalArgumentException();
        }
    }
    
    public void construct() {
    }
    
    public void setMember(int index, java.lang.Object memberValue) {
        try {
            switch(index) {
                case myJOURNEYINFO_1_INDEX:
                    _instance.setJourneyInfo_1((com.irctc.web.provider.JourneyInfo)memberValue);
                    break;
                case myPASSENGERINFO_2_INDEX:
                    _instance.setPassengerInfo_2((com.irctc.web.provider.PassengerInfo)memberValue);
                    break;
                default:
                    throw new java.lang.IllegalArgumentException();
            }
        }
        catch (java.lang.RuntimeException e) {
            throw e;
        }
        catch (java.lang.Exception e) {
            throw new DeserializationException(new LocalizableExceptionAdapter(e));
        }
    }
    
    public void initialize() {
    }
    
    public void setInstance(java.lang.Object instance) {
        _instance = (com.irctc.web.provider.IRCTCTicket_bookTicket_RequestStruct)instance;
    }
    
    public java.lang.Object getInstance() {
        return _instance;
    }
}
