// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.irctc.web.provider;


public class IRCTCTicket_getOffer_RequestStruct {
    protected java.lang.String String_1;
    
    public IRCTCTicket_getOffer_RequestStruct() {
    }
    
    public IRCTCTicket_getOffer_RequestStruct(java.lang.String String_1) {
        this.String_1 = String_1;
    }
    
    public java.lang.String getString_1() {
        return String_1;
    }
    
    public void setString_1(java.lang.String String_1) {
        this.String_1 = String_1;
    }
}
