// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.ola.partner.service;

import javax.xml.rpc.*;

public interface Ola_Service extends javax.xml.rpc.Service {
    public com.ola.partner.service.Ola_PortType getOlaSOAPPort() throws ServiceException;
}
