// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.ola.partner.service;


public class Ola_bookRide_RequestStruct2 {
    protected com.ola.partner.service.Trip trip;
    protected com.ola.partner.service.Passenger passenger;
    
    public Ola_bookRide_RequestStruct2() {
    }
    
    public Ola_bookRide_RequestStruct2(com.ola.partner.service.Trip trip, com.ola.partner.service.Passenger passenger) {
        this.trip = trip;
        this.passenger = passenger;
    }
    
    public com.ola.partner.service.Trip getTrip() {
        return trip;
    }
    
    public void setTrip(com.ola.partner.service.Trip trip) {
        this.trip = trip;
    }
    
    public com.ola.partner.service.Passenger getPassenger() {
        return passenger;
    }
    
    public void setPassenger(com.ola.partner.service.Passenger passenger) {
        this.passenger = passenger;
    }
}
