// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.ola.partner.service;

import com.sun.xml.rpc.server.http.MessageContextProperties;
import com.sun.xml.rpc.streaming.*;
import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.soap.SOAPConstants;
import com.sun.xml.rpc.encoding.soap.SOAP12Constants;
import com.sun.xml.rpc.encoding.literal.*;
import com.sun.xml.rpc.soap.streaming.*;
import com.sun.xml.rpc.soap.message.*;
import com.sun.xml.rpc.soap.SOAPVersion;
import com.sun.xml.rpc.soap.SOAPEncodingConstants;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;
import javax.xml.namespace.QName;
import java.rmi.RemoteException;
import java.util.Iterator;
import java.lang.reflect.*;
import java.lang.Class;
import com.sun.xml.rpc.client.SenderException;
import com.sun.xml.rpc.client.*;
import com.sun.xml.rpc.client.http.*;
import javax.xml.rpc.handler.*;
import javax.xml.rpc.JAXRPCException;
import javax.xml.rpc.soap.SOAPFaultException;

public class Ola_PortType_Stub
    extends com.sun.xml.rpc.client.StubBase
    implements com.ola.partner.service.Ola_PortType {
    
    
    
    /*
     *  public constructor
     */
    public Ola_PortType_Stub(HandlerChain handlerChain) {
        super(handlerChain);
        _setProperty(ENDPOINT_ADDRESS_PROPERTY, "http://localhost:8080/Ola/olaRide");
    }
    
    
    /*
     *  implementation of bookRide
     */
    public com.ola.partner.service.RideDetails bookRide(com.ola.partner.service.Trip trip, com.ola.partner.service.Passenger passenger)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(bookRide_OPCODE);
            com.ola.partner.service.Ola_bookRide_RequestStruct2 _myOla_bookRide_RequestStruct2 =
                new com.ola.partner.service.Ola_bookRide_RequestStruct2();
            
            _myOla_bookRide_RequestStruct2.setTrip(trip);
            _myOla_bookRide_RequestStruct2.setPassenger(passenger);
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_bookRide_bookRide_QNAME);
            _bodyBlock.setValue(_myOla_bookRide_RequestStruct2);
            _bodyBlock.setSerializer(ns1_myOla_bookRide_RequestStruct2_SOAPSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "http://ola.com/cabs/services#bookRide");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            com.ola.partner.service.Ola_bookRide_ResponseStruct2 _myOla_bookRide_ResponseStruct2 = null;
            Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _myOla_bookRide_ResponseStruct2 =
                    (com.ola.partner.service.Ola_bookRide_ResponseStruct2)((SOAPDeserializationState)_responseObj).getInstance();
            } else {
                _myOla_bookRide_ResponseStruct2 =
                    (com.ola.partner.service.Ola_bookRide_ResponseStruct2)_responseObj;
            }
            
            return _myOla_bookRide_ResponseStruct2.getResult();
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    
    /*
     *  this method deserializes the request/response structure in the body
     */
    protected void _readFirstBodyElement(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState  state) throws Exception {
        int opcode = state.getRequest().getOperationCode();
        switch (opcode) {
            case bookRide_OPCODE:
                _deserialize_bookRide(bodyReader, deserializationContext, state);
                break;
            default:
                throw new SenderException("sender.response.unrecognizedOperation", java.lang.Integer.toString(opcode));
        }
    }
    
    
    
    /*
     * This method deserializes the body of the bookRide operation.
     */
    private void _deserialize_bookRide(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myOla_bookRide_ResponseStruct2Obj =
            ns1_myOla_bookRide_ResponseStruct2_SOAPSerializer.deserialize(ns1_bookRide_bookRideResponse_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_bookRide_bookRideResponse_QNAME);
        bodyBlock.setValue(myOla_bookRide_ResponseStruct2Obj);
        state.getResponse().setBody(bodyBlock);
    }
    
    
    
    public java.lang.String _getDefaultEnvelopeEncodingStyle() {
        return SOAPNamespaceConstants.ENCODING;
    }
    
    public java.lang.String _getImplicitEnvelopeEncodingStyle() {
        return "";
    }
    
    public java.lang.String _getEncodingStyle() {
        return SOAPNamespaceConstants.ENCODING;
    }
    
    public void _setEncodingStyle(java.lang.String encodingStyle) {
        throw new UnsupportedOperationException("cannot set encoding style");
    }
    
    
    
    
    
    /*
     * This method returns an array containing (prefix, nsURI) pairs.
     */
    protected java.lang.String[] _getNamespaceDeclarations() {
        return myNamespace_declarations;
    }
    
    /*
     * This method returns an array containing the names of the headers we understand.
     */
    public javax.xml.namespace.QName[] _getUnderstoodHeaders() {
        return understoodHeaderNames;
    }
    
    
    protected void _preHandlingHook(StreamingSenderState state) throws Exception {
        super._preHandlingHook(state);
    }
    
    
    protected boolean _preRequestSendingHook(StreamingSenderState state) throws Exception {
        boolean bool = false;
        bool = super._preRequestSendingHook(state);
        return bool;
    }
    
    public void _initialize(InternalTypeMappingRegistry registry) throws Exception {
        super._initialize(registry);
        ns1_myOla_bookRide_RequestStruct2_SOAPSerializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, com.ola.partner.service.Ola_bookRide_RequestStruct2.class, ns1_bookRide_TYPE_QNAME);
        ns1_myOla_bookRide_ResponseStruct2_SOAPSerializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, com.ola.partner.service.Ola_bookRide_ResponseStruct2.class, ns1_bookRideResponse_TYPE_QNAME);
    }
    
    private static final javax.xml.namespace.QName _portName = new QName("http://ola.com/cabs/services", "olaSOAPPort");
    private static final int bookRide_OPCODE = 0;
    private static final javax.xml.namespace.QName ns1_bookRide_bookRide_QNAME = new QName("http://ola.com/cabs/services", "bookRide");
    private static final javax.xml.namespace.QName ns1_bookRide_TYPE_QNAME = new QName("http://ola.com/cabs/services", "bookRide");
    private CombinedSerializer ns1_myOla_bookRide_RequestStruct2_SOAPSerializer;
    private static final javax.xml.namespace.QName ns1_bookRide_bookRideResponse_QNAME = new QName("http://ola.com/cabs/services", "bookRideResponse");
    private static final javax.xml.namespace.QName ns1_bookRideResponse_TYPE_QNAME = new QName("http://ola.com/cabs/services", "bookRideResponse");
    private CombinedSerializer ns1_myOla_bookRide_ResponseStruct2_SOAPSerializer;
    private static final java.lang.String[] myNamespace_declarations =
                                        new java.lang.String[] {
                                            "ns0", "http://ola.com/cabs/services",
                                            "ns1", "http://ola.com/cabs/types"
                                        };
    
    private static final QName[] understoodHeaderNames = new QName[] {  };
}
