// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.ola.partner.service;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.literal.DetailFragmentDeserializer;
import com.sun.xml.rpc.encoding.simpletype.*;
import com.sun.xml.rpc.encoding.soap.SOAPConstants;
import com.sun.xml.rpc.encoding.soap.SOAP12Constants;
import com.sun.xml.rpc.streaming.*;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;
import javax.xml.namespace.QName;

public class Ola_bookRide_RequestStruct2_SOAPSerializer extends ObjectSerializerBase implements Initializable {
    private static final javax.xml.namespace.QName ns1_trip_QNAME = new QName("", "trip");
    private static final javax.xml.namespace.QName ns2_trip_TYPE_QNAME = new QName("http://ola.com/cabs/types", "trip");
    private CombinedSerializer ns2_myTrip_SOAPSerializer;
    private static final javax.xml.namespace.QName ns1_passenger_QNAME = new QName("", "passenger");
    private static final javax.xml.namespace.QName ns2_passenger_TYPE_QNAME = new QName("http://ola.com/cabs/types", "passenger");
    private CombinedSerializer ns2_myPassenger_SOAPSerializer;
    private static final int myTRIP_INDEX = 0;
    private static final int myPASSENGER_INDEX = 1;
    
    public Ola_bookRide_RequestStruct2_SOAPSerializer(QName type, boolean encodeType, boolean isNullable, String encodingStyle) {
        super(type, encodeType, isNullable, encodingStyle);
    }
    
    public void initialize(InternalTypeMappingRegistry registry) throws java.lang.Exception {
        ns2_myTrip_SOAPSerializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, com.ola.partner.service.Trip.class, ns2_trip_TYPE_QNAME);
        ns2_myPassenger_SOAPSerializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, com.ola.partner.service.Passenger.class, ns2_passenger_TYPE_QNAME);
    }
    
    public java.lang.Object doDeserialize(SOAPDeserializationState state, XMLReader reader,
        SOAPDeserializationContext context) throws java.lang.Exception {
        com.ola.partner.service.Ola_bookRide_RequestStruct2 instance = new com.ola.partner.service.Ola_bookRide_RequestStruct2();
        com.ola.partner.service.Ola_bookRide_RequestStruct2_SOAPBuilder builder = null;
        java.lang.Object member;
        boolean isComplete = true;
        javax.xml.namespace.QName elementName;
        
        reader.nextElementContent();
        for (int i=0; i<2; i++) {
            elementName = reader.getName();
            if (reader.getState() == XMLReader.END) {
                break;
            }
            if (elementName.equals(ns1_trip_QNAME)) {
                member = ns2_myTrip_SOAPSerializer.deserialize(ns1_trip_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.ola.partner.service.Ola_bookRide_RequestStruct2_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myTRIP_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setTrip((com.ola.partner.service.Trip)member);
                }
                reader.nextElementContent();
                continue;
            }
            if (elementName.equals(ns1_passenger_QNAME)) {
                member = ns2_myPassenger_SOAPSerializer.deserialize(ns1_passenger_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.ola.partner.service.Ola_bookRide_RequestStruct2_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myPASSENGER_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setPassenger((com.ola.partner.service.Passenger)member);
                }
                reader.nextElementContent();
                continue;
            } else {
                throw new DeserializationException("soap.unexpectedElementName", new Object[] {ns1_passenger_QNAME, elementName});
            }
        }
        
        XMLReaderUtil.verifyReaderState(reader, XMLReader.END);
        return (isComplete ? (java.lang.Object)instance : (java.lang.Object)state);
    }
    
    public void doSerializeAttributes(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        com.ola.partner.service.Ola_bookRide_RequestStruct2 instance = (com.ola.partner.service.Ola_bookRide_RequestStruct2)obj;
        
    }
    
    public void doSerializeInstance(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        com.ola.partner.service.Ola_bookRide_RequestStruct2 instance = (com.ola.partner.service.Ola_bookRide_RequestStruct2)obj;
        
        ns2_myTrip_SOAPSerializer.serialize(instance.getTrip(), ns1_trip_QNAME, null, writer, context);
        ns2_myPassenger_SOAPSerializer.serialize(instance.getPassenger(), ns1_passenger_QNAME, null, writer, context);
    }
}
