// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.ola.partner.service;

public interface Ola_PortType extends java.rmi.Remote {
    public com.ola.partner.service.RideDetails bookRide(com.ola.partner.service.Trip trip, com.ola.partner.service.Passenger passenger) throws 
         java.rmi.RemoteException;
}
