// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.ola.partner.service;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.client.ServiceExceptionImpl;
import com.sun.xml.rpc.util.exception.*;
import com.sun.xml.rpc.soap.SOAPVersion;
import com.sun.xml.rpc.client.HandlerChainImpl;
import javax.xml.rpc.*;
import javax.xml.rpc.encoding.*;
import javax.xml.rpc.handler.HandlerChain;
import javax.xml.rpc.handler.HandlerInfo;
import javax.xml.namespace.QName;

public class Ola_Service_Impl extends com.sun.xml.rpc.client.BasicService implements Ola_Service {
    private static final QName serviceName = new QName("http://ola.com/cabs/services", "ola");
    private static final QName ns1_olaSOAPPort_QNAME = new QName("http://ola.com/cabs/services", "olaSOAPPort");
    private static final Class ola_PortType_PortClass = com.ola.partner.service.Ola_PortType.class;
    
    public Ola_Service_Impl() {
        super(serviceName, new QName[] {
                        ns1_olaSOAPPort_QNAME
                    },
            new com.ola.partner.service.Ola_Service_SerializerRegistry().getRegistry());
        
    }
    
    public java.rmi.Remote getPort(javax.xml.namespace.QName portName, java.lang.Class serviceDefInterface) throws javax.xml.rpc.ServiceException {
        try {
            if (portName.equals(ns1_olaSOAPPort_QNAME) &&
                serviceDefInterface.equals(ola_PortType_PortClass)) {
                return getOlaSOAPPort();
            }
        } catch (Exception e) {
            throw new ServiceExceptionImpl(new LocalizableExceptionAdapter(e));
        }
        return super.getPort(portName, serviceDefInterface);
    }
    
    public java.rmi.Remote getPort(java.lang.Class serviceDefInterface) throws javax.xml.rpc.ServiceException {
        try {
            if (serviceDefInterface.equals(ola_PortType_PortClass)) {
                return getOlaSOAPPort();
            }
        } catch (Exception e) {
            throw new ServiceExceptionImpl(new LocalizableExceptionAdapter(e));
        }
        return super.getPort(serviceDefInterface);
    }
    
    public com.ola.partner.service.Ola_PortType getOlaSOAPPort() {
        java.lang.String[] roles = new java.lang.String[] {};
        HandlerChainImpl handlerChain = new HandlerChainImpl(getHandlerRegistry().getHandlerChain(ns1_olaSOAPPort_QNAME));
        handlerChain.setRoles(roles);
        com.ola.partner.service.Ola_PortType_Stub stub = new com.ola.partner.service.Ola_PortType_Stub(handlerChain);
        try {
            stub._initialize(super.internalTypeRegistry);
        } catch (JAXRPCException e) {
            throw e;
        } catch (Exception e) {
            throw new JAXRPCException(e.getMessage(), e);
        }
        return stub;
    }
}
