// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.ola.partner.service;


public class RideDetails {
    protected java.lang.String cabNo;
    protected java.lang.String driverName;
    protected java.lang.String driverMobileNo;
    protected float estimatedAmount;
    
    public RideDetails() {
    }
    
    public RideDetails(java.lang.String cabNo, java.lang.String driverName, java.lang.String driverMobileNo, float estimatedAmount) {
        this.cabNo = cabNo;
        this.driverName = driverName;
        this.driverMobileNo = driverMobileNo;
        this.estimatedAmount = estimatedAmount;
    }
    
    public java.lang.String getCabNo() {
        return cabNo;
    }
    
    public void setCabNo(java.lang.String cabNo) {
        this.cabNo = cabNo;
    }
    
    public java.lang.String getDriverName() {
        return driverName;
    }
    
    public void setDriverName(java.lang.String driverName) {
        this.driverName = driverName;
    }
    
    public java.lang.String getDriverMobileNo() {
        return driverMobileNo;
    }
    
    public void setDriverMobileNo(java.lang.String driverMobileNo) {
        this.driverMobileNo = driverMobileNo;
    }
    
    public float getEstimatedAmount() {
        return estimatedAmount;
    }
    
    public void setEstimatedAmount(float estimatedAmount) {
        this.estimatedAmount = estimatedAmount;
    }
}
