// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.ola.partner.service;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.util.exception.LocalizableExceptionAdapter;

public class Trip_SOAPBuilder implements SOAPInstanceBuilder {
    private com.ola.partner.service.Trip _instance;
    private java.lang.String source;
    private java.lang.String destination;
    private java.lang.String cabType;
    private java.lang.String promoCode;
    private static final int mySOURCE_INDEX = 0;
    private static final int myDESTINATION_INDEX = 1;
    private static final int myCABTYPE_INDEX = 2;
    private static final int myPROMOCODE_INDEX = 3;
    
    public Trip_SOAPBuilder() {
    }
    
    public void setSource(java.lang.String source) {
        this.source = source;
    }
    
    public void setDestination(java.lang.String destination) {
        this.destination = destination;
    }
    
    public void setCabType(java.lang.String cabType) {
        this.cabType = cabType;
    }
    
    public void setPromoCode(java.lang.String promoCode) {
        this.promoCode = promoCode;
    }
    
    public int memberGateType(int memberIndex) {
        switch (memberIndex) {
            case mySOURCE_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myDESTINATION_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myCABTYPE_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myPROMOCODE_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            default:
                throw new IllegalArgumentException();
        }
    }
    
    public void construct() {
    }
    
    public void setMember(int index, java.lang.Object memberValue) {
        try {
            switch(index) {
                case mySOURCE_INDEX:
                    _instance.setSource((java.lang.String)memberValue);
                    break;
                case myDESTINATION_INDEX:
                    _instance.setDestination((java.lang.String)memberValue);
                    break;
                case myCABTYPE_INDEX:
                    _instance.setCabType((java.lang.String)memberValue);
                    break;
                case myPROMOCODE_INDEX:
                    _instance.setPromoCode((java.lang.String)memberValue);
                    break;
                default:
                    throw new java.lang.IllegalArgumentException();
            }
        }
        catch (java.lang.RuntimeException e) {
            throw e;
        }
        catch (java.lang.Exception e) {
            throw new DeserializationException(new LocalizableExceptionAdapter(e));
        }
    }
    
    public void initialize() {
    }
    
    public void setInstance(java.lang.Object instance) {
        _instance = (com.ola.partner.service.Trip)instance;
    }
    
    public java.lang.Object getInstance() {
        return _instance;
    }
}
